"""Genereaza assets/continut/{categorie}/intrebari.json pentru cele patru
categorii noi, complet diferite tematic de restul jocului: steaguri, animale,
monumente, instrumente (4 variante, 3 hinturi, imagine_cautare pentru
tools/images/fetch_question_images.py).

Spre deosebire de restul categoriilor, aici numarul de intrebari NU e fixat
la 100 - fiecare categorie are atatea intrari unice, de calitate, cate au
existat disponibile (intre ~50 si ~70), la cererea explicita a userului.
Daca un item nu are imagine gasita de fetch_question_images.py, jocul arata
un placeholder text "Va urma" (vezi BlurImage._fallback) in loc sa blocheze
categoria.

Fiecare item: (raspuns, termen_cautare_imagine_EN, hint1, hint2, hint3, [3 variante gresite])
Rulare: python tools/questions/generate_world_categories.py [steaguri animale monumente instrumente]
        (fara argumente = toate cele patru)
"""
import io
import json
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

STEAGURI_ITEMS = [
    ("FRANTA", "Flag of France", "Trei culori verticale: albastru, alb, roșu", "Se numește Le Tricolore", "Capitala e Paris", ["ITALIA", "OLANDA", "BELGIA"]),
    ("ITALIA", "Flag of Italy", "Trei culori verticale: verde, alb, roșu", "Foarte asemănător cu steagul Mexicului", "Capitala e Roma", ["FRANTA", "MEXIC", "UNGARIA"]),
    ("GERMANIA", "Flag of Germany", "Trei benzi orizontale: negru, roșu, galben", "Capitala e Berlin", "Cea mai mare economie din Europa", ["BELGIA", "AUSTRIA", "OLANDA"]),
    ("SPANIA", "Flag of Spain", "Are o stemă pe partea stângă", "Benzi orizontale roșu-galben-roșu", "Capitala e Madrid", ["PORTUGALIA", "ITALIA", "MEXIC"]),
    ("REGATUL UNIT", "Flag of the United Kingdom", "Se numește Union Jack", "Combină crucile Angliei, Scoției și Irlandei", "Capitala e Londra", ["AUSTRALIA", "NOUA ZEELANDA", "STATELE UNITE ALE AMERICII"]),
    ("STATELE UNITE ALE AMERICII", "Flag of the United States", "Are 50 de stele și 13 dungi", "Se numește Stars and Stripes", "Capitala e Washington D.C.", ["REGATUL UNIT", "LIBERIA", "MALAEZIA"]),
    ("CANADA", "Flag of Canada", "Are o frunză roșie în centru", "Frunza e de arțar", "Capitala e Ottawa", ["STATELE UNITE ALE AMERICII", "AUSTRIA", "ELVETIA"]),
    ("BRAZILIA", "Flag of Brazil", "Verde cu un romb galben și un glob albastru", "Pe glob scrie 'Ordem e Progresso'", "Cea mai mare țară din America de Sud", ["ARGENTINA", "MEXIC", "PORTUGALIA"]),
    ("ARGENTINA", "Flag of Argentina", "Dungi orizontale albastru-alb-albastru", "Are un soare auriu în mijloc", "Capitala e Buenos Aires", ["URUGUAY", "BRAZILIA", "CHILE"]),
    ("MEXIC", "Flag of Mexico", "Verde-alb-roșu cu o stemă în mijloc", "Stema arată un vultur pe un cactus", "Capitala e Ciudad de Mexico", ["ITALIA", "BRAZILIA", "SPANIA"]),
    ("JAPONIA", "Flag of Japan", "Un cerc roșu pe fundal alb", "Se numește Hinomaru", "Supranumită 'Țara Soarelui Răsare'", ["COREEA DE SUD", "BANGLADESH", "CHINA"]),
    ("CHINA", "Flag of China", "Roșu cu cinci stele galbene", "O stea mare și patru mai mici", "Cea mai populată țară din lume", ["VIETNAM", "JAPONIA", "COREEA DE SUD"]),
    ("COREEA DE SUD", "Flag of South Korea", "Are un simbol Yin-Yang în centru", "Patru trigrame în colțuri", "Capitala e Seul", ["JAPONIA", "CHINA", "MONGOLIA"]),
    ("INDIA", "Flag of India", "Portocaliu, alb, verde cu o roată albastră", "Roata se numește Ashoka Chakra", "A doua cea mai populată țară din lume", ["NEPAL", "BANGLADESH", "SRI LANKA"]),
    ("AUSTRALIA", "Flag of Australia", "Are Union Jack în colț și stele albe", "Stelele formează Crucea Sudului", "E și continent, și țară", ["NOUA ZEELANDA", "REGATUL UNIT", "STATELE UNITE ALE AMERICII"]),
    ("RUSIA", "Flag of Russia", "Trei benzi orizontale: alb, albastru, roșu", "Cea mai mare țară din lume ca suprafață", "Capitala e Moscova", ["SLOVACIA", "SERBIA", "OLANDA"]),
    ("UCRAINA", "Flag of Ukraine", "Două benzi orizontale: albastru și galben", "Albastrul reprezintă cerul, galbenul câmpurile de grâu", "Capitala e Kiev", ["SUEDIA", "ROMANIA", "RUSIA"]),
    ("POLONIA", "Flag of Poland", "Două benzi orizontale: alb sus, roșu jos", "Capitala e Varșovia", "Vecină cu Germania la vest", ["INDONEZIA", "MONACO", "UCRAINA"]),
    ("OLANDA", "Flag of the Netherlands", "Trei benzi orizontale: roșu, alb, albastru", "Cunoscută și ca Țările de Jos", "Capitala e Amsterdam", ["LUXEMBURG", "FRANTA", "RUSIA"]),
    ("BELGIA", "Flag of Belgium", "Trei benzi verticale: negru, galben, roșu", "Capitala e Bruxelles", "Cunoscută pentru ciocolată și vafe", ["GERMANIA", "ROMANIA", "CIAD"]),
    ("ELVETIA", "Flag of Switzerland", "O cruce albă pe fundal roșu", "Unul din doar două steaguri pătrate din lume", "Capitala e Berna", ["AUSTRIA", "DANEMARCA", "CANADA"]),
    ("AUSTRIA", "Flag of Austria", "Trei benzi orizontale: roșu, alb, roșu", "Capitala e Viena", "Patria lui Mozart", ["LETONIA", "ELVETIA", "POLONIA"]),
    ("SUEDIA", "Flag of Sweden", "Fundal albastru cu o cruce galbenă", "Capitala e Stockholm", "Cunoscută pentru mobilierul IKEA", ["NORVEGIA", "FINLANDA", "ISLANDA"]),
    ("NORVEGIA", "Flag of Norway", "Cruce albastră cu contur alb pe fundal roșu", "Capitala e Oslo", "Cunoscută pentru fiorduri", ["ISLANDA", "SUEDIA", "DANEMARCA"]),
    ("FINLANDA", "Flag of Finland", "Fundal alb cu o cruce albastră", "Capitala e Helsinki", "Supranumită 'Țara celor o mie de lacuri'", ["SUEDIA", "GRECIA", "ISRAEL"]),
    ("DANEMARCA", "Flag of Denmark", "Fundal roșu cu o cruce albă", "Cel mai vechi steag național încă folosit", "Capitala e Copenhaga", ["NORVEGIA", "ELVETIA", "AUSTRIA"]),
    ("ISLANDA", "Flag of Iceland", "Cruce albastră cu alb pe fundal roșu", "Capitala e Reykjavik", "Țară cu vulcani și gheizere", ["NORVEGIA", "DANEMARCA", "FINLANDA"]),
    ("IRLANDA", "Flag of Ireland", "Trei benzi verticale: verde, alb, portocaliu", "Capitala e Dublin", "Supranumită 'Insula Smarald'", ["ITALIA", "COASTA DE FILDES", "NIGERIA"]),
    ("PORTUGALIA", "Flag of Portugal", "Verde și roșu cu o stemă complexă", "Capitala e Lisabona", "Vecină cu Spania pe Peninsula Iberică", ["SPANIA", "MOZAMBIC", "ANGOLA"]),
    ("GRECIA", "Flag of Greece", "Dungi albastre-albe cu o cruce în colț", "Capitala e Atena", "Locul unde au apărut Jocurile Olimpice", ["FINLANDA", "URUGUAY", "ISRAEL"]),
    ("TURCIA", "Flag of Turkey", "Roșu cu o semilună și o stea albă", "Capitala e Ankara, dar Istanbul e cel mai mare oraș", "Se întinde pe două continente", ["TUNISIA", "PAKISTAN", "ALGERIA"]),
    ("EGIPT", "Flag of Egypt", "Trei benzi orizontale cu un vultur auriu în mijloc", "Capitala e Cairo", "Țara piramidelor și a Nilului", ["IRAK", "SIRIA", "YEMEN"]),
    ("AFRICA DE SUD", "Flag of South Africa", "Șase culori, formă de Y", "Unul dintre cele mai colorate steaguri din lume", "Capitala administrativă e Pretoria", ["KENYA", "NIGERIA", "ETIOPIA"]),
    ("NIGERIA", "Flag of Nigeria", "Trei benzi verticale: verde, alb, verde", "Cea mai populată țară din Africa", "Capitala e Abuja", ["IRLANDA", "ITALIA", "MALI"]),
    ("KENYA", "Flag of Kenya", "Negru, roșu, verde cu un scut masai în centru", "Capitala e Nairobi", "Celebră pentru safariuri", ["ETIOPIA", "TANZANIA", "AFRICA DE SUD"]),
    ("MAROC", "Flag of Morocco", "Roșu cu o stea verde cu cinci colțuri", "Capitala e Rabat", "Țară din nordul Africii, aproape de Spania", ["TUNISIA", "ALGERIA", "ARABIA SAUDITA"]),
    ("ARABIA SAUDITA", "Flag of Saudi Arabia", "Verde cu text arab și o sabie", "Aici se află orașul sfânt Mecca", "Cel mai mare exportator de petrol din lume", ["EMIRATELE ARABE UNITE", "IRAN", "QATAR"]),
    ("EMIRATELE ARABE UNITE", "Flag of the United Arab Emirates", "Roșu, verde, alb, negru", "Aici se află Dubai și Burj Khalifa", "Formată din șapte emirate", ["ARABIA SAUDITA", "QATAR", "KUWEIT"]),
    ("ISRAEL", "Flag of Israel", "Steaua lui David albastră pe fundal alb", "Capitala declarată e Ierusalim", "Vecin cu Egiptul și Iordania", ["GRECIA", "ARGENTINA", "UNGARIA"]),
    ("IRAN", "Flag of Iran", "Verde, alb, roșu cu o emblemă în mijloc", "Capitala e Teheran", "Cunoscut și sub numele istoric de Persia", ["ARABIA SAUDITA", "IRAK", "TURCIA"]),
    ("PAKISTAN", "Flag of Pakistan", "Verde cu o semilună și o stea, dungă albă lateral", "Capitala e Islamabad", "Vecin cu India și Afganistan", ["TURCIA", "MAURITANIA", "ALGERIA"]),
    ("INDONEZIA", "Flag of Indonesia", "Două benzi orizontale: roșu sus, alb jos", "Cea mai mare țară formată din insule", "Capitala e Jakarta", ["MONACO", "POLONIA", "SINGAPORE"]),
    ("THAILANDA", "Flag of Thailand", "Cinci benzi orizontale: roșu, alb, albastru, alb, roșu", "Singura țară din Asia de Sud-Est niciodată colonizată", "Capitala e Bangkok", ["COSTA RICA", "CHILE", "LUXEMBURG"]),
    ("VIETNAM", "Flag of Vietnam", "Roșu cu o stea galbenă mare în centru", "Capitala e Hanoi", "Cunoscut pentru orezării și Golful Ha Long", ["CHINA", "MAROC", "MOZAMBIC"]),
    ("FILIPINE", "Flag of the Philippines", "Albastru, roșu și un triunghi alb cu soare", "Un arhipelag format din mii de insule", "Capitala e Manila", ["CUBA", "MALAEZIA", "INDONEZIA"]),
    ("MALAEZIA", "Flag of Malaysia", "Dungi roșu-alb cu o lună și stea pe albastru", "Seamănă cu steagul SUA la prima vedere", "Capitala e Kuala Lumpur", ["STATELE UNITE ALE AMERICII", "SINGAPORE", "FILIPINE"]),
    ("SINGAPORE", "Flag of Singapore", "Roșu și alb cu o semilună și cinci stele", "Un oraș-stat foarte mic și bogat", "Are unul dintre cele mai aglomerate porturi din lume", ["INDONEZIA", "MALAEZIA", "VIETNAM"]),
    ("NOUA ZEELANDA", "Flag of New Zealand", "Are Union Jack și Crucea Sudului roșie", "Foarte asemănător cu steagul Australiei", "Capitala e Wellington", ["AUSTRALIA", "REGATUL UNIT", "FIJI"]),
    ("COLUMBIA", "Flag of Colombia", "Trei benzi orizontale: galben, albastru, roșu", "Galbenul ocupă jumătate din steag", "Capitala e Bogotá", ["ECUADOR", "VENEZUELA", "BRAZILIA"]),
    ("CHILE", "Flag of Chile", "Are o stea albă pe fundal albastru, deasupra alb-roșu", "O țară foarte lungă și îngustă", "Capitala e Santiago", ["PERU", "ARGENTINA", "URUGUAY"]),
    ("PERU", "Flag of Peru", "Trei benzi verticale: roșu, alb, roșu", "Aici se află Machu Picchu", "Capitala e Lima", ["CANADA", "AUSTRIA", "LETONIA"]),
    ("CUBA", "Flag of Cuba", "Are o stea albă într-un triunghi roșu", "Cea mai mare insulă din Caraibe", "Capitala e Havana", ["PUERTO RICO", "FILIPINE", "CHILE"]),
    ("JAMAICA", "Flag of Jamaica", "O cruce diagonală galbenă pe verde și negru", "Singurul steag național fără roșu, alb sau albastru", "Patria reggae-ului și a lui Bob Marley", ["ETIOPIA", "GHANA", "SENEGAL"]),
    ("CROATIA", "Flag of Croatia", "Roșu-alb-albastru cu o stemă în carouri", "Stema are model de tablă de șah", "Capitala e Zagreb", ["SERBIA", "SLOVENIA", "UNGARIA"]),
    ("SERBIA", "Flag of Serbia", "Roșu, albastru, alb cu o stemă", "Capitala e Belgrad", "Fostă parte din Iugoslavia", ["RUSIA", "SLOVACIA", "CROATIA"]),
    ("BULGARIA", "Flag of Bulgaria", "Trei benzi orizontale: alb, verde, roșu", "Vecină la sud cu România", "Capitala e Sofia", ["UNGARIA", "SIERRA LEONE", "MADAGASCAR"]),
    ("UNGARIA", "Flag of Hungary", "Trei benzi orizontale: roșu, alb, verde", "Vecină la vest cu România", "Capitala e Budapesta", ["BULGARIA", "ITALIA", "IRLANDA"]),
    ("CEHIA", "Flag of the Czech Republic", "Alb-roșu cu un triunghi albastru lateral", "Capitala e Praga", "Fostă parte din Cehoslovacia", ["POLONIA", "SLOVACIA", "AUSTRIA"]),
    ("SLOVACIA", "Flag of Slovakia", "Alb, albastru, roșu cu o stemă", "Capitala e Bratislava", "S-a separat pașnic de Cehia în 1993", ["RUSIA", "SLOVENIA", "SERBIA"]),
    ("GEORGIA", "Flag of Georgia", "Alb cu o cruce roșie mare și patru cruci mici", "Capitala e Tbilisi", "Țară din Caucaz, între Europa și Asia", ["ARMENIA", "AZERBAIDJAN", "ELVETIA"]),
    ("KAZAHSTAN", "Flag of Kazakhstan", "Albastru cu un soare auriu și un vultur", "Cea mai mare țară din lume fără ieșire la ocean", "Capitala e Astana", ["MONGOLIA", "UZBEKISTAN", "RUSIA"]),
    ("MONGOLIA", "Flag of Mongolia", "Roșu-albastru-roșu cu un simbol auriu Soyombo", "Patria lui Genghis Han", "Una dintre cele mai slab populate țări din lume", ["KAZAHSTAN", "COREEA DE NORD", "CHINA"]),
    ("NEPAL", "Flag of Nepal", "Singurul steag național care nu e dreptunghiular", "Format din două triunghiuri suprapuse", "Aici se află Muntele Everest", ["BHUTAN", "INDIA", "TIBET"]),
    ("BHUTAN", "Flag of Bhutan", "Un dragon alb pe diagonală galben-portocaliu", "Supranumită 'Țara Dragonului Tunet'", "Măsoară fericirea națională, nu doar economia", ["NEPAL", "MONGOLIA", "LAOS"]),
    ("ETIOPIA", "Flag of Ethiopia", "Verde, galben, roșu cu o stea albastră", "Una dintre puținele țări africane niciodată colonizate", "Se crede locul de origine al cafelei", ["GHANA", "MALI", "SENEGAL"]),
    ("VENEZUELA", "Flag of Venezuela", "Galben, albastru, roșu cu opt stele albe", "Capitala e Caracas", "Are cele mai mari rezerve de petrol dovedite din lume", ["COLUMBIA", "ECUADOR", "BRAZILIA"]),
    ("URUGUAY", "Flag of Uruguay", "Nouă dungi orizontale și un 'Soare al lui Mai' în colț", "Capitala e Montevideo", "Una dintre cele mai mici țări din America de Sud", ["ARGENTINA", "PARAGUAY", "CHILE"]),
    ("ECUADOR", "Flag of Ecuador", "Galben, albastru, roșu, cu o stemă complexă în mijloc", "Numele înseamnă 'ecuator' în spaniolă", "Aici se află Insulele Galapagos", ["COLUMBIA", "VENEZUELA", "PERU"]),
    ("COSTA RICA", "Flag of Costa Rica", "Cinci benzi: albastru, alb, roșu gros, alb, albastru", "Nu are armată din 1949", "Capitala e San José", ["THAILANDA", "PANAMA", "CUBA"]),
    ("PANAMA", "Flag of Panama", "Patru pătrate: alb cu stea albastră, roșu, albastru, alb cu stea roșie", "Aici se află celebrul canal care leagă cele două oceane", "Capitala e Panama City", ["COSTA RICA", "VENEZUELA", "CUBA"]),
    ("LITUANIA", "Flag of Lithuania", "Trei benzi orizontale: galben, verde, roșu", "Capitala e Vilnius", "Cea mai sudică dintre țările baltice", ["LETONIA", "ESTONIA", "BULGARIA"]),
    ("LETONIA", "Flag of Latvia", "Roșu-grena cu o dungă albă îngustă la mijloc", "Capitala e Riga", "Una dintre cele trei țări baltice", ["LITUANIA", "ESTONIA", "AUSTRIA"]),
    ("ESTONIA", "Flag of Estonia", "Trei benzi orizontale: albastru, negru, alb", "Capitala e Tallinn", "Cea mai nordică dintre țările baltice", ["LETONIA", "LITUANIA", "FINLANDA"]),
    ("SLOVENIA", "Flag of Slovenia", "Alb, albastru, roșu cu o stemă cu munte și stele", "Capitala e Ljubljana", "Fostă parte din Iugoslavia, ca și Croația", ["CROATIA", "SLOVACIA", "SERBIA"]),
    ("ALBANIA", "Flag of Albania", "Roșu cu un vultur bicefal negru în mijloc", "Capitala e Tirana", "Vecină cu Grecia și Muntenegru", ["MUNTENEGRU", "MACEDONIA DE NORD", "SERBIA"]),
    ("MOLDOVA", "Flag of Moldova", "Albastru, galben, roșu cu o stemă cu cap de bour", "Capitala e Chișinău", "Vecină la est cu România", ["ROMANIA", "UCRAINA", "BULGARIA"]),
    ("ARMENIA", "Flag of Armenia", "Trei benzi orizontale: roșu, albastru, portocaliu", "Capitala e Erevan", "Prima țară din lume care a adoptat creștinismul ca religie de stat", ["GEORGIA", "AZERBAIDJAN", "IRAN"]),
    ("AZERBAIDJAN", "Flag of Azerbaijan", "Albastru, roșu, verde cu o semilună și o stea", "Capitala e Baku", "Țară bogată în petrol, la Marea Caspică", ["ARMENIA", "GEORGIA", "TURCIA"]),
    ("SRI LANKA", "Flag of Sri Lanka", "Un leu cu sabie pe fundal grena, cu dungi verzi și portocalii", "O insulă aflată sub India", "Cunoscută pentru ceai și scorțișoară", ["INDIA", "BANGLADESH", "NEPAL"]),
    ("LIBAN", "Flag of Lebanon", "Roșu-alb-roșu cu un cedru verde în mijloc", "Cedrul e simbolul național", "Capitala e Beirut", ["SIRIA", "IORDANIA", "ISRAEL"]),
    ("IORDANIA", "Flag of Jordan", "Negru, alb, verde cu un triunghi roșu și o stea", "Capitala e Amman", "Vecină cu Israel, Siria, Irak și Arabia Saudită", ["LIBAN", "SIRIA", "EGIPT"]),
    ("TUNISIA", "Flag of Tunisia", "Roșu cu un disc alb, semilună și stea", "Capitala e Tunis", "Aici a început 'Primăvara Arabă' în 2010-2011", ["MAROC", "ALGERIA", "TURCIA"]),
    ("GHANA", "Flag of Ghana", "Roșu, galben, verde cu o stea neagră în mijloc", "Prima țară din Africa subsahariană care și-a câștigat independența", "Capitala e Accra", ["JAMAICA", "ETIOPIA", "SENEGAL"]),
    ("MADAGASCAR", "Flag of Madagascar", "Alb vertical lângă două benzi orizontale roșu-verde", "A patra cea mai mare insulă din lume", "Cunoscută pentru lemuri, specii unice pe Pământ", ["KENYA", "GHANA", "MOZAMBIC"]),
    ("CIPRU", "Flag of Cyprus", "Alb cu harta insulei în auriu și două ramuri de măslin", "Singurul steag național cu harta propriei țări pe el", "Insulă împărțită între greci și turci", ["MALTA", "GRECIA", "LIBAN"]),
    ("MALTA", "Flag of Malta", "Alb-roșu cu Crucea Sfântului Gheorghe în colț", "Una dintre cele mai mici țări din Uniunea Europeană", "Capitala e Valletta", ["CIPRU", "MONACO", "SAN MARINO"]),
    ("LUXEMBURG", "Flag of Luxembourg", "Roșu, alb, albastru deschis, orizontal", "Aproape identic cu steagul Olandei", "Unul dintre cele mai bogate state din lume, per capita", ["OLANDA", "BELGIA", "MONACO"]),
    ("VATICAN", "Flag of Vatican City", "Galben și alb, cu o stemă papală", "Cel mai mic stat independent din lume", "Aflat complet în interiorul orașului Roma", ["ITALIA", "SAN MARINO", "MALTA"]),
]

ANIMALE_ITEMS = [
    ("LEUL", "Lion animal", "Supranumit 'Regele junglei'", "Doar masculul are coamă", "Trăiește în grupuri numite haite (mândrii)", ["TIGRUL", "LEOPARDUL", "PUMA"]),
    ("TIGRUL", "Tiger animal", "Cea mai mare felină sălbatică din lume", "Are dungi unice, ca amprentele", "Trăiește solitar, spre deosebire de leu", ["LEUL", "LEOPARDUL", "GHEPARDUL"]),
    ("ELEFANTUL AFRICAN", "African elephant", "Cel mai mare animal terestru", "Are urechi mari, în formă de Africa", "Colții sunt de fapt dinți uriași", ["RINOCERUL", "HIPOPOTAMUL", "GIRAFA"]),
    ("GIRAFA", "Giraffe animal", "Are cel mai lung gât dintre mamifere", "Modelul blănii e unic la fiecare individ", "Trăiește în savana africană", ["CAMILA", "ELANUL", "ZEBRA"]),
    ("ZEBRA", "Zebra animal", "Are dungi albe și negre unice fiecărui individ", "Rudă apropiată cu calul", "Trăiește în turme mari, în Africa", ["GIRAFA", "GAZELA", "GNU"]),
    ("RINOCERUL", "Rhinoceros animal", "Are unul sau două coarne pe bot", "Coarnele sunt din keratină, ca unghiile", "Piele foarte groasă, ca o armură", ["HIPOPOTAMUL", "ELEFANTUL AFRICAN", "BIVOLUL AFRICAN"]),
    ("HIPOPOTAMUL", "Hippopotamus animal", "Petrece cea mai mare parte a zilei în apă", "Unul dintre cele mai periculoase animale din Africa", "Numele înseamnă 'calul de râu'", ["RINOCERUL", "MORSA", "CROCODILUL DE NIL"]),
    ("GORILA", "Gorilla animal", "Cea mai mare maimuță din lume", "Masculii adulți se numesc 'spate argintiu'", "Trăiește în pădurile tropicale din Africa", ["CIMPANZEUL", "URSUL PANDA", "LENESUL DE COPAC"]),
    ("CIMPANZEUL", "Chimpanzee animal", "Cea mai apropiată rudă a omului", "Folosește unelte simple, ca bețe", "Trăiește în grupuri sociale complexe", ["GORILA", "URSUL LENES", "LEMUR"]),
    ("URSUL PANDA", "Giant panda animal", "Alb-negru, mănâncă mai ales bambus", "Simbolul conservării speciilor pe cale de dispariție", "Trăiește în munții din China", ["URSUL POLAR", "URSUL BRUN", "URSUL LENES"]),
    ("URSUL POLAR", "Polar bear animal", "Cel mai mare carnivor terestru", "Blana pare albă, dar pielea de dedesubt e neagră", "Vânează foci pe gheața Arcticii", ["URSUL PANDA", "URSUL BRUN", "MORSA"]),
    ("URSUL BRUN", "Brown bear animal", "Poate cântări peste 300 de kilograme", "Hibernează iarna în bârlog", "Trăiește și în munții din România", ["URSUL POLAR", "URSUL PANDA", "LUPUL"]),
    ("LUPUL", "Gray wolf animal", "Trăiește și vânează în haită", "Strămoșul sălbatic al câinelui domestic", "Comunică prin urlete", ["VULPEA", "RASUL", "HIENA"]),
    ("VULPEA", "Red fox animal", "Are blană roșcată și coadă stufoasă", "Foarte adaptabilă, trăiește și la oraș", "Cunoscută pentru viclenie în povești", ["LUPUL", "RASUL", "CASTORUL"]),
    ("CANGURUL", "Kangaroo animal", "Sare pe picioarele din spate, puternice", "Puii cresc într-un marsupiu", "Simbol al Australiei", ["KOALA", "WOMBAT", "CASOARUL"]),
    ("KOALA", "Koala animal", "Se hrănește aproape exclusiv cu frunze de eucalipt", "Doarme până la 20 de ore pe zi", "Un marsupiu, nu un urs, deși pare așa", ["CANGURUL", "URSUL PANDA", "LENESUL DE COPAC"]),
    ("STRUTUL", "Ostrich bird", "Cea mai mare pasăre din lume", "Nu poate zbura, dar aleargă foarte repede", "Ouăle lui sunt cele mai mari dintre toate păsările", ["CASOARUL", "PELICANUL", "PAUNUL"]),
    ("FLAMINGO", "Flamingo bird", "Culoarea roz vine din hrana pe bază de alge și crustacee", "Stă adesea într-un picior", "Trăiește în stoluri mari, în lagune", ["PELICANUL", "TUCANUL", "PAUNUL"]),
    ("PINGUINUL", "Emperor penguin", "Pasăre care nu zboară, dar înoată excelent", "Trăiește în Antarctica, la temperaturi extreme", "Masculul clocește oul pe picioare, sub un pliu de piele", ["FOCA", "MORSA", "PELICANUL"]),
    ("BALENA ALBASTRA", "Blue whale animal", "Cel mai mare animal care a trăit vreodată pe Pământ", "Inima ei cântărește cât o mașină mică", "Se hrănește cu krill, creaturi minuscule", ["DELFINUL", "MANTA", "RECHINUL ALB"]),
    ("DELFINUL", "Dolphin animal", "Foarte inteligent, comunică prin sunete", "Trăiește în grupuri numite școli", "Vine des la suprafață să respire aer", ["BALENA ALBASTRA", "FOCA", "MANTA"]),
    ("RECHINUL ALB", "Great white shark", "Cel mai mare pește prădător din ocean", "Are simțul mirosului extrem de fin", "Făcut celebru de filmul 'Fălci'", ["RECHINUL CIOCAN", "MANTA", "BALENA ALBASTRA"]),
    ("CARACATITA", "Octopus animal", "Are opt tentacule și trei inimi", "Poate să-și schimbe culoarea instant", "Una dintre cele mai inteligente nevertebrate", ["MEDUZA", "STEAUA DE MARE", "CALUTUL DE MARE"]),
    ("MEDUZA", "Jellyfish animal", "Corp gelatinos, aproape transparent", "Unele specii au înțepătură dureroasă", "Nu are creier, inimă sau oase", ["CARACATITA", "STEAUA DE MARE", "MANTA"]),
    ("TESTOASA URIASA", "Galapagos giant tortoise", "Poate trăi peste 100 de ani", "Printre cele mai longevive animale din lume", "Trăiește pe insulele Galapagos", ["CROCODILUL DE NIL", "IGUANA", "VARANUL DE KOMODO"]),
    ("CROCODILUL DE NIL", "Nile crocodile", "Unul dintre cei mai mari prădători de apă dulce", "Stă la pândă aproape nemișcat înainte de atac", "Trăiește în râurile și lacurile Africii", ["ALIGATORUL AMERICAN", "VARANUL DE KOMODO", "TESTOASA URIASA"]),
    ("ALIGATORUL AMERICAN", "American alligator", "Botul mai lat decât al crocodilului", "Trăiește în mlaștinile din sud-estul SUA", "Poate rămâne nemișcat ore întregi", ["CROCODILUL DE NIL", "IGUANA", "VARANUL DE KOMODO"]),
    ("COBRA REGALA", "King cobra snake", "Cel mai lung șarpe veninos din lume", "Își poate ridica o treime din corp", "Gâtul se lățește când se simte amenințată", ["PITONUL", "IGUANA", "VARANUL DE KOMODO"]),
    ("PITONUL", "Python snake", "Ucide prin sufocare, nu prin venin", "Unele specii pot depăși 6 metri lungime", "Își înghite prada întreagă", ["COBRA REGALA", "IGUANA", "CAMELEONUL"]),
    ("IGUANA", "Iguana animal", "Are un rând de țepi de-a lungul spatelui", "Foarte bună la cățărat și înot", "Trăiește mai ales în America Centrală și de Sud", ["CAMELEONUL", "VARANUL DE KOMODO", "COBRA REGALA"]),
    ("CAMELEONUL", "Chameleon animal", "Își schimbă culoarea pielii", "Ochii se pot mișca independent unul de altul", "Limba lui e mai lungă decât propriul corp", ["IGUANA", "VARANUL DE KOMODO", "PITONUL"]),
    ("VARANUL DE KOMODO", "Komodo dragon", "Cea mai mare șopârlă din lume", "Trăiește doar pe câteva insule din Indonezia", "Are salivă cu bacterii periculoase pentru pradă", ["CROCODILUL DE NIL", "IGUANA", "TESTOASA URIASA"]),
    ("VULTURUL PLESUV", "Bald eagle bird", "Simbolul național al Statelor Unite", "Capul alb apare abia la maturitate", "Are vedere de câteva ori mai bună decât omul", ["BUFNITA", "SOIMUL CALATOR", "PELICANUL"]),
    ("BUFNITA", "Owl bird", "Vânează mai ales noaptea", "Poate roti capul aproape complet", "Zboară aproape fără zgomot", ["VULTURUL PLESUV", "PELICANUL", "TUCANUL"]),
    ("PAPAGALUL ARA", "Macaw parrot", "Are pene extrem de colorate", "Poate imita sunete și cuvinte", "Trăiește în pădurile tropicale din America de Sud", ["TUCANUL", "COLIBRI", "PAUNUL"]),
    ("COLIBRI", "Hummingbird", "Cea mai mică pasăre din lume", "Aripile bat de zeci de ori pe secundă", "Singura pasăre care poate zbura cu spatele", ["PAPAGALUL ARA", "TUCANUL", "FLAMINGO"]),
    ("LENESUL DE COPAC", "Sloth animal", "Unul dintre cele mai lente animale din lume", "Petrece aproape toată viața agățat în copaci", "Coboară la sol doar o dată pe săptămână", ["URSUL LENES", "KOALA", "FURNICARUL"]),
    ("FURNICARUL", "Anteater animal", "Se hrănește cu furnici și termite, folosind limba lungă", "Nu are dinți deloc", "Are gheare puternice pentru săpat mușuroaie", ["ARMADILLO", "LENESUL DE COPAC", "URSUL LENES"]),
    ("ARMADILLO", "Armadillo animal", "Corpul acoperit cu o carapace osoasă", "Unele specii se pot rula într-o minge", "Trăiește mai ales în America de Sud", ["FURNICARUL", "LENESUL DE COPAC", "ARICIUL"]),
    ("LAMA", "Llama animal", "Rudă a cămilei, dar fără cocoașă", "Folosită ca animal de povară în Anzi", "Poate scuipa când e supărată", ["CAMILA", "ELANUL", "RENUL"]),
    ("BIZONUL AMERICAN", "American bison", "Cel mai mare mamifer terestru din America de Nord", "Aproape a dispărut în secolul XIX", "Simbol al preriilor din Vestul Sălbatic", ["BIVOLUL AFRICAN", "ELANUL", "RENUL"]),
    ("ELANUL", "Moose animal", "Cel mai mare cerb din lume", "Masculii au coarne late, ca niște palme", "Trăiește în pădurile din nordul Europei și Americii", ["RENUL", "BIZONUL AMERICAN", "CAMILA"]),
    ("RENUL", "Reindeer animal", "Singurul cerb la care ambele sexe au coarne", "Trăiește în regiunile arctice", "Asociat cu sania lui Moș Crăciun", ["ELANUL", "LAMA", "BIZONUL AMERICAN"]),
    ("RASUL", "Lynx animal", "Are smocuri de păr în vârful urechilor", "Coada scurtă, tăiată parcă", "Trăiește și în pădurile din Carpați", ["PUMA", "LEOPARDUL", "VULPEA"]),
    ("PUMA", "Cougar animal", "Cunoscută și ca 'leul de munte'", "Nu poate mârâi, doar torcei ca o pisică mare", "Trăiește pe un teritoriu foarte întins, din Canada până în Chile", ["JAGUARUL", "LEOPARDUL", "RASUL"]),
    ("JAGUARUL", "Jaguar animal", "Cea mai mare felină din America", "Are cea mai puternică mușcătură dintre feline", "Modelul blănii seamănă cu al leopardului, dar cu pete mai mari", ["LEOPARDUL", "PUMA", "GHEPARDUL"]),
    ("LEOPARDUL", "Leopard animal", "Foarte bun cățărător, își duce prada în copaci", "Modelul blănii se numește 'rozetă'", "Trăiește atât în Africa, cât și în Asia", ["JAGUARUL", "GHEPARDUL", "TIGRUL"]),
    ("GHEPARDUL", "Cheetah animal", "Cel mai rapid animal terestru din lume", "Are 'urme de lacrimi' negre sub ochi", "Vânează prin sprint scurt, nu prin anduranță", ["LEOPARDUL", "PUMA", "RASUL"]),
    ("HIENA", "Spotted hyena", "Are un răget care seamănă cu un râs", "Trăiește în clanuri conduse de femele", "Adesea confundată cu un prădător doar de resturi", ["LUPUL", "GAZELA", "GNU"]),
    ("GAZELA", "Gazelle animal", "Foarte rapidă, cu sărituri înalte de alertă", "Prada de bază a leilor și gheparzilor în savană", "Trăiește în turme mari, în Africa și Asia", ["GNU", "ZEBRA", "BIVOLUL AFRICAN"]),
    ("GNU", "Wildebeest animal", "Participă la cea mai mare migrație de mamifere din lume", "Are cap masiv și coarne curbate", "Trăiește în turme uriașe în Africa de Est", ["GAZELA", "BIVOLUL AFRICAN", "ZEBRA"]),
    ("BIVOLUL AFRICAN", "African buffalo", "Unul dintre 'cei cinci mari' din safariurile africane", "Foarte periculos când e rănit sau încolțit", "Trăiește în turme mari, cu coarne masive", ["GNU", "RINOCERUL", "HIPOPOTAMUL"]),
    ("CAMILA", "Camel animal", "Depozitează grăsime în cocoașă, nu apă", "Poate merge zile întregi fără să bea", "Adaptată perfect vieții în deșert", ["LAMA", "GIRAFA", "ELANUL"]),
    ("URSUL LENES", "Sloth bear animal", "Se hrănește mai ales cu termite și fructe", "Blană lungă, zbârlită", "Trăiește în India și Sri Lanka", ["URSUL PANDA", "GORILA", "LENESUL DE COPAC"]),
    ("CASTORUL", "Beaver animal", "Construiește baraje din lemn pe râuri", "Are dinți din față care cresc continuu", "Coada lată, plată, folosită ca vâslă", ["VIDRA", "VULPEA", "ARICIUL"]),
    ("VIDRA", "Otter animal", "Foarte jucăușă, se dă pe tobogane de noroi", "Unele specii sparg scoici folosind pietre", "Blană extrem de deasă, care o ține uscată în apă", ["CASTORUL", "FOCA", "MORSA"]),
    ("VEVERITA", "Squirrel animal", "Îngroapă alune și ghinde pentru iarnă", "Coadă mare, stufoasă", "Foarte des întâlnită în parcuri și păduri", ["ARICIUL", "CASTORUL", "LILIACUL"]),
    ("ARICIUL", "Hedgehog animal", "Corpul acoperit cu țepi", "Se face ghem când se simte amenințat", "Activ mai ales noaptea", ["ARMADILLO", "VEVERITA", "CASTORUL"]),
    ("LILIACUL", "Bat animal", "Singurul mamifer capabil de zbor propulsat", "Multe specii se orientează prin ecolocație", "Activ noaptea, doarme atârnat cu capul în jos", ["VEVERITA", "BUFNITA", "COLIBRI"]),
    ("RECHINUL CIOCAN", "Hammerhead shark", "Capul lățit, în formă de ciocan", "Forma capului îi dă vedere aproape completă în jur", "Trăiește în ape calde, tropicale", ["RECHINUL ALB", "MANTA", "DELFINUL"]),
    ("CALUTUL DE MARE", "Seahorse animal", "Masculul e cel care poartă puii, nu femela", "Înoată vertical, foarte încet", "Capul seamănă cu cel al unui cal mic", ["STEAUA DE MARE", "PESTELE CLOWN", "MANTA"]),
    ("STEAUA DE MARE", "Starfish animal", "De obicei are cinci brațe", "Își poate regenera un braț pierdut", "Nu are creier sau sânge, ca majoritatea animalelor", ["CALUTUL DE MARE", "MEDUZA", "CARACATITA"]),
    ("PESTELE CLOWN", "Clownfish animal", "Trăiește în siguranță printre tentaculele anemonelor", "Devenit celebru prin filmul 'Nemo'", "Are dungi portocalii și albe", ["CALUTUL DE MARE", "MANTA", "STEAUA DE MARE"]),
    ("MANTA", "Manta ray animal", "Un pește uriaș, plat, care 'zboară' prin apă", "Se hrănește filtrând plancton", "Aripioarele laterale seamănă cu niște aripi", ["RECHINUL CIOCAN", "PESTELE CLOWN", "BALENA ALBASTRA"]),
    ("FOCA", "Seal animal", "Înoată excelent, dar se mișcă stângaci pe uscat", "Are un strat gros de grăsime pentru izolare termică", "Se hrănește mai ales cu pește", ["MORSA", "PINGUINUL", "VIDRA"]),
    ("MORSA", "Walrus animal", "Are colți lungi, vizibili chiar și cu gura închisă", "Trăiește în regiunile arctice", "Piele groasă, cu riduri", ["FOCA", "URSUL POLAR", "HIPOPOTAMUL"]),
    ("TUCANUL", "Toucan bird", "Are un cioc uriaș, colorat, dar foarte ușor", "Trăiește în pădurile tropicale din America de Sud", "Ciocul îl ajută să ajungă la fructe pe crengi subțiri", ["PAPAGALUL ARA", "FLAMINGO", "PAUNUL"]),
    ("PAUNUL", "Peacock bird", "Masculul își desface coada într-un evantai colorat", "Penele au 'ochi' iridescenți", "Folosește coada pentru a atrage femelele", ["FLAMINGO", "TUCANUL", "PAPAGALUL ARA"]),
    ("VULTURUL DE AUR", "Golden eagle bird", "Unul dintre cei mai mari și puternici răpitori din emisfera nordică", "Vânează iepuri și chiar căprioare tinere", "Trăiește și în munții din România", ["VULTURUL PLESUV", "SOIMUL CALATOR", "BUFNITA"]),
    ("MARMOTA", "Marmot animal", "Trăiește în văgăuni săpate la altitudine mare", "Hibernează în grup, mai multe luni pe an", "Scoate un fluierat ascuțit când simte pericol", ["VEVERITA", "BURSUCUL", "ARICIUL"]),
    ("BURSUCUL", "Badger animal", "Sapă vizuini complexe, cu multe camere și tuneluri", "Are dungi albe și negre pe cap", "Activ mai ales noaptea", ["MARMOTA", "VIDRA", "DIHORUL"]),
    ("DIHORUL", "Polecat animal", "Rudă sălbatică a nurcii domestice (dihor de casă)", "Eliberează un miros puternic când se apără", "Vânează șoareci și șobolani", ["BURSUCUL", "VULPEA", "VIDRA"]),
    ("SURICATA", "Meerkat animal", "Stă în picioare, dreaptă, ca o santinelă", "Trăiește în grupuri mari, în deșertul Kalahari", "Membrii grupului se schimbă la 'pază'", ["MARMOTA", "DIHORUL", "ARICIUL"]),
    ("ORCA", "Orca killer whale animal", "Numită și 'balena ucigașă', deși e de fapt un delfin uriaș", "Neagră cu alb, foarte ușor de recunoscut", "Vânează în grupuri organizate, ca lupii", ["DELFINUL", "BALENA ALBASTRA", "RECHINUL ALB"]),
    ("RECHINUL BALENA", "Whale shark animal", "Cel mai mare pește din lume", "Cu toate că e uriaș, se hrănește doar cu plancton", "Are pielea acoperită cu model de puncte", ["BALENA ALBASTRA", "MANTA", "RECHINUL ALB"]),
    ("BROASCA TESTOASA DE MARE", "Sea turtle animal", "Înoată mii de kilometri pentru a se întoarce la plaja natală", "Femelele ies pe uscat doar ca să depună ouă", "Are picioarele transformate în înotătoare", ["TESTOASA URIASA", "MANTA", "FOCA"]),
    ("ZIMBRUL EUROPEAN", "European bison animal", "Cel mai greu mamifer terestru din Europa", "A fost readus în sălbăticie după ce a dispărut aproape complet", "Trăiește și în pădurile din România", ["BIZONUL AMERICAN", "BIVOLUL AFRICAN", "ELANUL"]),
    ("CAPRA NEAGRA", "Chamois animal", "Trăiește pe stânci abrupte, la altitudine mare", "Sare cu ușurință între stânci greu accesibile", "Simbol al munților din România (Carpați)", ["RASUL", "URSUL BRUN", "MARMOTA"]),
    ("VULPEA POLARA", "Arctic fox animal", "Blana devine albă iarna și cenușie-maro vara", "Trăiește în tundra din jurul Polului Nord", "Suportă temperaturi extrem de scăzute", ["URSUL POLAR", "VULPEA", "RENUL"]),
    ("ALBATROSUL", "Albatross bird", "Are cea mai mare anvergură a aripilor dintre toate păsările", "Poate pluti deasupra oceanului zile întregi fără să bată din aripi", "Se întoarce pe uscat doar ca să se reproducă", ["CONDORUL", "PELICANUL", "VULTURUL DE AUR"]),
    ("CONDORUL", "Andean condor bird", "Una dintre cele mai mari păsări zburătoare din lume", "Trăiește în munții Anzi", "Se hrănește mai ales cu animale moarte (necrofag)", ["ALBATROSUL", "VULTURUL PLESUV", "VULTURUL HARPIA"]),
    ("VULTURUL HARPIA", "Harpy eagle bird", "Una dintre cele mai puternice păsări răpitoare din lume", "Vânează maimuțe și lenești direct din copaci", "Trăiește în pădurile tropicale din America de Sud", ["VULTURUL DE AUR", "CONDORUL", "VULTURUL PLESUV"]),
    ("IEPURELE", "Hare animal", "Are picioare din spate lungi și puternice, pentru sărituri rapide", "Diferit de iepurele de casă, puii lui se nasc cu blană", "Foarte rapid, folosește viteza ca apărare", ["VEVERITA", "ARICIUL", "VULPEA"]),
]

MONUMENTE_ITEMS = [
    ("TURNUL EIFFEL", "Eiffel Tower Paris", "Construit pentru Expoziția Universală din 1889", "Din fier, aproape 330 de metri înălțime", "Simbolul orașului Paris", ["ARCUL DE TRIUMF", "NOTRE-DAME", "TURNUL LONDREI"]),
    ("MARELE ZID CHINEZESC", "Great Wall of China", "Se întinde pe mii de kilometri", "Construit de-a lungul secolelor pentru apărare", "Vizibil parțial din spațiu, potrivit unei legende populare", ["TEMPLUL BOROBUDUR", "FORTUL ROSU", "ANGKOR WAT"]),
    ("TAJ MAHAL", "Taj Mahal India", "Construit de un împărat mogul în memoria soției sale", "Din marmură albă", "Aflat în orașul Agra, India", ["FORTUL ROSU", "TEMPLUL AURIU", "PALATUL VERSAILLES"]),
    ("COLOSSEUMUL", "Colosseum Rome", "Cel mai mare amfiteatru antic construit vreodată", "Aici aveau loc luptele de gladiatori", "Aflat în centrul Romei", ["ACROPOLE", "PARTENON", "PODUL RIALTO"]),
    ("STATUIA LIBERTATII", "Statue of Liberty New York", "Un cadou al Franței pentru Statele Unite", "Ține o torță ridicată în mână", "Aflată pe o insulă din portul New York", ["CRISTO REDENTOR", "EMPIRE STATE BUILDING", "SEMNUL HOLLYWOOD"]),
    ("BIG BEN", "Big Ben London", "Numele oficial al clopotului, nu al turnului", "Parte a Palatului Westminster", "Simbolul Londrei", ["TOWER BRIDGE", "TURNUL LONDREI", "PALATUL BUCKINGHAM"]),
    ("PODUL GOLDEN GATE", "Golden Gate Bridge San Francisco", "Vopsit într-o culoare portocalie specială", "Leagă San Francisco de comitatul Marin", "Unul dintre cele mai fotografiate poduri din lume", ["TURNUL CN", "EMPIRE STATE BUILDING", "ALCATRAZ"]),
    ("OPERA DIN SYDNEY", "Sydney Opera House", "Acoperișul seamănă cu niște pânze de corabie", "Aflată pe malul portului din Sydney", "Una dintre clădirile secolului XX cele mai ușor recognoscibile", ["TURNUL CN", "ULURU", "MAREA BARIERA DE CORALI"]),
    ("TURNUL DIN PISA", "Leaning Tower of Pisa", "Celebru pentru înclinarea sa neintenționată", "Construit ca turn clopotniță", "Aflat în orașul Pisa, Italia", ["COLOSSEUMUL", "FANTANA DI TREVI", "PODUL RIALTO"]),
    ("MACHU PICCHU", "Machu Picchu Peru", "O cetate incașă construită în munți", "Aflată la mare altitudine, în Anzi", "Redescoperită pentru lumea occidentală în 1911", ["CHICHEN ITZA", "STATUILE MOAI", "TEMPLUL KARNAK"]),
    ("PIRAMIDELE DIN GIZA", "Pyramids of Giza", "Singura minune antică a lumii încă în picioare", "Construite ca morminte pentru faraoni", "Aflate lângă orașul Cairo", ["SFINXUL", "ABU SIMBEL", "TEMPLUL KARNAK"]),
    ("SFINXUL", "Great Sphinx of Giza", "Are corp de leu și cap de om", "Sculptat direct din stâncă", "Stă chiar lângă piramidele din Giza", ["PIRAMIDELE DIN GIZA", "ABU SIMBEL", "TEMPLUL KARNAK"]),
    ("PETRA", "Petra Jordan", "Un oraș antic sculptat direct în stâncă roz", "Ascuns între munți, în Iordania", "Faimos datorită clădirii numite 'Vistieria'", ["CHICHEN ITZA", "ABU SIMBEL", "ANGKOR WAT"]),
    ("STONEHENGE", "Stonehenge England", "Un cerc din pietre uriașe, ridicate în preistorie", "Scopul exact rămâne un mister", "Aflat în sudul Angliei", ["CASTELUL EDINBURGH", "TURNUL LONDREI", "TOWER BRIDGE"]),
    ("CATEDRALA SFANTUL VASILE", "Saint Basil's Cathedral Moscow", "Cunoscută pentru cupolele colorate, în formă de ceapă", "Aflată în Piața Roșie din Moscova", "Construită la ordinul lui Ivan cel Groaznic", ["KREMLIN", "CATEDRALA DIN KOLN", "BAZILICA SFANTUL PETRU"]),
    ("NOTRE-DAME", "Notre-Dame de Paris", "O catedrală gotică aflată pe o insulă din Sena", "Cunoscută datorită romanului lui Victor Hugo", "A suferit un incendiu major în 2019", ["SAGRADA FAMILIA", "CATEDRALA DIN KOLN", "TURNUL EIFFEL"]),
    ("SAGRADA FAMILIA", "Sagrada Familia Barcelona", "O basilică proiectată de arhitectul Antoni Gaudí", "Încă neterminată, deși construcția a început în 1882", "Aflată în Barcelona, Spania", ["NOTRE-DAME", "CATEDRALA DIN KOLN", "TURNUL DIN PISA"]),
    ("MONT SAINT-MICHEL", "Mont Saint-Michel", "O insulă-mănăstire aflată pe coasta Franței", "Înconjurată de apă doar la maree mare", "Silueta ei seamănă cu un castel din povești", ["CASTELUL NEUSCHWANSTEIN", "CASTELUL EDINBURGH", "PODUL RIALTO"]),
    ("CASTELUL NEUSCHWANSTEIN", "Neuschwanstein Castle", "A inspirat castelul din siglele Disney", "Construit de regele Ludovic al II-lea al Bavariei", "Aflat pe un deal din sudul Germaniei", ["MONT SAINT-MICHEL", "CASTELUL EDINBURGH", "CATEDRALA DIN KOLN"]),
    ("CRISTO REDENTOR", "Christ the Redeemer statue Rio", "O statuie uriașă cu brațele deschise", "Privește orașul Rio de Janeiro de pe un munte", "Una dintre noile șapte minuni ale lumii moderne", ["STATUIA LIBERTATII", "STATUILE MOAI", "MAREA BARIERA DE CORALI"]),
    ("CHICHEN ITZA", "Chichen Itza Mexico", "O piramidă maya în trepte, în Mexic", "În zilele de echinocțiu apare umbra unui șarpe pe trepte", "Una dintre noile șapte minuni ale lumii moderne", ["MACHU PICCHU", "PETRA", "TEMPLUL BOROBUDUR"]),
    ("ANGKOR WAT", "Angkor Wat Cambodia", "Cel mai mare complex religios din lume", "Construit inițial ca templu hindus, apoi budist", "Aflat în Cambodgia", ["TEMPLUL BOROBUDUR", "MARELE ZID CHINEZESC", "TEMPLUL AURIU"]),
    ("BURJ KHALIFA", "Burj Khalifa Dubai", "Cea mai înaltă clădire din lume", "Aflată în Dubai, Emiratele Arabe Unite", "Are peste 160 de etaje", ["TURNUL TOKYO", "EMPIRE STATE BUILDING", "TURNUL CN"]),
    ("TURNUL TOKYO", "Tokyo Tower", "Vopsit alb-portocaliu, inspirat de Turnul Eiffel", "Folosit și ca turn de comunicații", "Aflat în capitala Japoniei", ["BURJ KHALIFA", "TURNUL EIFFEL", "TURNUL CN"]),
    ("POARTA BRANDENBURG", "Brandenburg Gate Berlin", "Simbolul reunificării Germaniei", "Are o statuie cu un car tras de cai deasupra", "Aflată în centrul Berlinului", ["ARCUL DE TRIUMF", "CATEDRALA DIN KOLN", "CASA ALBA"]),
    ("ARCUL DE TRIUMF", "Arc de Triomphe Paris", "Comandat de Napoleon în cinstea armatei sale", "Aflat pe Champs-Élysées, în Paris", "Sub el arde o flacără veșnică", ["POARTA BRANDENBURG", "TURNUL EIFFEL", "NOTRE-DAME"]),
    ("TURNUL LONDREI", "Tower of London", "O fortăreață veche, folosită și ca închisoare", "Aici sunt păzite bijuteriile coroanei britanice", "Aflat pe malul Tamisei", ["TOWER BRIDGE", "BIG BEN", "PALATUL BUCKINGHAM"]),
    ("PALATUL BUCKINGHAM", "Buckingham Palace", "Reședința oficială a monarhului britanic la Londra", "Are loc schimbarea gărzii în fața lui", "Are peste 700 de camere", ["TURNUL LONDREI", "BIG BEN", "CASTELUL EDINBURGH"]),
    ("EMPIRE STATE BUILDING", "Empire State Building New York", "Un zgârie-nori celebru din New York", "A fost cea mai înaltă clădire din lume mulți ani", "A apărut în filmul King Kong", ["BURJ KHALIFA", "STATUIA LIBERTATII", "SEMNUL HOLLYWOOD"]),
    ("SEMNUL HOLLYWOOD", "Hollywood Sign Los Angeles", "Nouă litere albe uriașe pe un deal", "Simbolul industriei filmului american", "Aflat deasupra orașului Los Angeles", ["EMPIRE STATE BUILDING", "ALCATRAZ", "PODUL GOLDEN GATE"]),
    ("ALCATRAZ", "Alcatraz Island prison", "O fostă închisoare de maximă siguranță, pe o insulă", "Aflată în golful San Francisco", "Considerată aproape imposibil de evadat", ["PODUL GOLDEN GATE", "SEMNUL HOLLYWOOD", "TURNUL CN"]),
    ("MUNTELE RUSHMORE", "Mount Rushmore", "Patru chipuri de președinți americani sculptate în stâncă", "Aflat în statul Dakota de Sud", "Fiecare cap are aproximativ 18 metri înălțime", ["STATUILE MOAI", "CRISTO REDENTOR", "STATUIA LIBERTATII"]),
    ("CASCADA NIAGARA", "Niagara Falls", "Un grup de cascade uriașe, la granița SUA-Canada", "Faimoasă pentru puterea și volumul apei", "Vizitată de milioane de turiști anual", ["MARELE CANION", "ULURU", "MAREA BARIERA DE CORALI"]),
    ("MARELE CANION", "Grand Canyon", "Săpat de-a lungul a milioane de ani de râul Colorado", "Unul dintre cele mai vizitate parcuri naturale din SUA", "Adânc de peste un kilometru în unele locuri", ["CASCADA NIAGARA", "ULURU", "MAREA BARIERA DE CORALI"]),
    ("ULURU", "Uluru Ayers Rock Australia", "O formațiune uriașă de rocă roșie, în inima Australiei", "Loc sacru pentru aborigenii australieni", "Își schimbă culoarea în funcție de lumina soarelui", ["MARELE CANION", "CASCADA NIAGARA", "MAREA BARIERA DE CORALI"]),
    ("MAREA BARIERA DE CORALI", "Great Barrier Reef", "Cel mai mare sistem de recifuri de corali din lume", "Vizibil chiar și din spațiu", "Aflată pe coasta de nord-est a Australiei", ["ULURU", "MARELE CANION", "CASCADA NIAGARA"]),
    ("TURNUL CN", "CN Tower Toronto", "Un turn de comunicații foarte înalt, în Canada", "A fost multă vreme cea mai înaltă structură de sine stătătoare din lume", "Are o podea de sticlă la înălțime", ["BURJ KHALIFA", "TURNUL TOKYO", "EMPIRE STATE BUILDING"]),
    ("CASA ALBA", "White House Washington", "Reședința oficială a președintelui SUA", "Aflată în Washington D.C.", "Vopsită complet în alb", ["PALATUL BUCKINGHAM", "PALATUL VERSAILLES", "POARTA BRANDENBURG"]),
    ("PALATUL VERSAILLES", "Palace of Versailles", "Fostă reședință a regilor Franței", "Celebru pentru Galeria Oglinzilor", "Aflat lângă Paris", ["CASA ALBA", "TAJ MAHAL", "PALATUL BUCKINGHAM"]),
    ("KREMLIN", "Moscow Kremlin", "O fortăreață care găzduiește guvernul rus", "Aflat chiar lângă Piața Roșie", "Are ziduri roșii și mai multe turnuri", ["CATEDRALA SFANTUL VASILE", "CATEDRALA DIN KOLN", "PALATUL VERSAILLES"]),
    ("ACROPOLE", "Acropolis of Athens", "O citadelă antică ridicată pe un deal stâncos", "Aici se află templul Partenon", "Simbolul Atenei și al Greciei antice", ["PARTENON", "COLOSSEUMUL", "TEMPLUL KARNAK"]),
    ("TEMPLUL BOROBUDUR", "Borobudur temple Indonesia", "Cel mai mare templu budist din lume", "Aflat pe insula Java, Indonezia", "Construit sub formă de mai multe platforme suprapuse", ["ANGKOR WAT", "TEMPLUL AURIU", "MARELE ZID CHINEZESC"]),
    ("TEMPLUL AURIU", "Golden Temple Amritsar", "Cel mai sacru templu al sikhilor", "Acoperit cu foiță de aur adevărat", "Aflat în orașul Amritsar, India", ["TAJ MAHAL", "FORTUL ROSU", "TEMPLUL BOROBUDUR"]),
    ("FORTUL ROSU", "Red Fort Delhi", "O fortăreață construită din gresie roșie", "Aflată în Delhi, India", "De aici se ține discursul anual de Ziua Independenței Indiei", ["TAJ MAHAL", "TEMPLUL AURIU", "PALATUL VERSAILLES"]),
    ("TOWER BRIDGE", "Tower Bridge London", "Un pod basculant, cu două turnuri", "Adesea confundat cu Turnul Londrei, aflat chiar lângă el", "Se deschide pentru a lăsa vasele mari să treacă", ["TURNUL LONDREI", "BIG BEN", "PODUL GOLDEN GATE"]),
    ("ATOMIUM", "Atomium Brussels", "Reprezintă un atom de fier mărit de miliarde de ori", "Construit pentru Expoziția Universală din 1958", "Aflat în Bruxelles, Belgia", ["TURNUL EIFFEL", "PODUL RIALTO", "CATEDRALA DIN KOLN"]),
    ("BUDDHA URIAS DE LA LESHAN", "Leshan Giant Buddha", "Cea mai mare statuie de Buddha sculptată în stâncă din lume", "Sculptată pe malul unui râu, în China", "Are peste 70 de metri înălțime", ["TEMPLUL AURIU", "TEMPLUL BOROBUDUR", "ANGKOR WAT"]),
    ("ZIDUL PLANGERII", "Western Wall Jerusalem", "Un loc sfânt pentru credința iudaică", "Rămășiță a vechiului Templu din Ierusalim", "Oamenii lasă bilețele cu rugăciuni printre pietre", ["CUPOLA STANCII", "BAZILICA SFANTUL PETRU", "TEMPLUL KARNAK"]),
    ("BAZILICA SFANTUL PETRU", "St Peter's Basilica Vatican", "Cea mai mare biserică din lume", "Aflată în Cetatea Vaticanului, la Roma", "Are o cupolă proiectată de Michelangelo", ["CATEDRALA SFANTUL VASILE", "NOTRE-DAME", "CATEDRALA DIN KOLN"]),
    ("FANTANA DI TREVI", "Trevi Fountain Rome", "Tradiția spune că arunci o monedă și te vei întoarce la Roma", "Cea mai mare fântână baroc din oraș", "Aflată în centrul istoric al Romei", ["PODUL RIALTO", "COLOSSEUMUL", "TURNUL DIN PISA"]),
    ("PODUL RIALTO", "Rialto Bridge Venice", "Cel mai vechi pod peste Marele Canal din Veneția", "Are prăvălii construite chiar pe el", "Simbolul orașului Veneția", ["FANTANA DI TREVI", "TURNUL DIN PISA", "TOWER BRIDGE"]),
    ("CASTELUL EDINBURGH", "Edinburgh Castle", "O fortăreață ridicată pe o stâncă vulcanică stinsă", "Domină orizontul capitalei Scoției", "Aici se păstrează bijuteriile coroanei scoțiene", ["MONT SAINT-MICHEL", "CASTELUL NEUSCHWANSTEIN", "STONEHENGE"]),
    ("STATUILE MOAI", "Moai statues Easter Island", "Capete și torsuri uriașe, sculptate în piatră", "Aflate pe Insula Paștelui, în Pacific", "Ridicate de civilizația Rapa Nui, cu multe secole în urmă", ["MUNTELE RUSHMORE", "CRISTO REDENTOR", "ULURU"]),
    ("TEMPLUL KARNAK", "Karnak Temple Egypt", "Cel mai mare complex de temple din Egiptul antic", "Aflat lângă orașul Luxor", "Are o sală cu zeci de coloane uriașe", ["ABU SIMBEL", "PIRAMIDELE DIN GIZA", "SFINXUL"]),
    ("ABU SIMBEL", "Abu Simbel temple", "Două temple uriașe sculptate în stâncă, în sudul Egiptului", "Construite de faraonul Ramses al II-lea", "Au fost mutate bucată cu bucată pentru a nu fi inundate", ["TEMPLUL KARNAK", "PIRAMIDELE DIN GIZA", "SFINXUL"]),
    ("CATEDRALA DIN KOLN", "Cologne Cathedral", "O catedrală gotică uriașă, în Germania", "A rămas aproape neatinsă în bombardamentele din al Doilea Război Mondial", "Are două turnuri gemene, foarte înalte", ["NOTRE-DAME", "SAGRADA FAMILIA", "BAZILICA SFANTUL PETRU"]),
    ("PODUL CHARLES", "Charles Bridge Prague", "Un pod istoric pietonal, decorat cu statui de sfinți", "Traversează râul Vltava", "Aflat în Praga, Cehia", ["TOWER BRIDGE", "PODUL RIALTO", "PODUL GOLDEN GATE"]),
    ("CASTELUL PRAGA", "Prague Castle", "Cel mai mare complex de castel antic din lume", "Domină orizontul capitalei cehe", "Reședință istorică a regilor Boemiei", ["CASTELUL NEUSCHWANSTEIN", "CASTELUL EDINBURGH", "MONT SAINT-MICHEL"]),
    ("HAGIA SOFIA", "Hagia Sophia Istanbul", "A fost pe rând biserică, moschee și muzeu", "Cunoscută pentru cupola sa uriașă", "Aflată în Istanbul, Turcia", ["ALBASTRA MOSCHEE", "TEMPLUL AURIU", "TEMPLUL BOROBUDUR"]),
    ("PIATA SAN MARCO", "St Mark's Square Venice", "Cea mai cunoscută piață publică din Veneția", "Deseori inundată de 'acqua alta'", "Aici se află Bazilica San Marco", ["PODUL RIALTO", "FANTANA DI TREVI", "TURNUL DIN PISA"]),
    ("SPACE NEEDLE", "Space Needle Seattle", "Un turn de observație construit pentru o expoziție universală din 1962", "Simbolul orașului Seattle", "Are formă futuristă, ca o farfurie zburătoare pe un stâlp", ["TURNUL CN", "TURNUL TOKYO", "BURJ KHALIFA"]),
    ("CRISTO REI", "Cristo Rei Lisbon statue", "O statuie a lui Isus cu brațele deschise, în Portugalia", "Inspirată direct de statuia din Rio de Janeiro", "Privește orașul Lisabona peste råu", ["CRISTO REDENTOR", "STATUIA LIBERTATII", "STATUILE MOAI"]),
    ("PODUL BROOKLYN", "Brooklyn Bridge New York", "Unul dintre cele mai vechi poduri suspendate din SUA", "Leagă Manhattan de Brooklyn", "Are turnuri din piatră, în stil gotic", ["PODUL GOLDEN GATE", "TOWER BRIDGE", "EMPIRE STATE BUILDING"]),
    ("TEMPLELE DIN BAGAN", "Bagan temples Myanmar", "Mii de temple și pagode antice, răspândite pe o câmpie", "Aflate în Myanmar (fosta Birmanie)", "Multe au peste 800 de ani vechime", ["ANGKOR WAT", "TEMPLUL BOROBUDUR", "TEMPLUL AURIU"]),
    ("MARELE PALAT REGAL", "Grand Palace Bangkok", "Fosta reședință oficială a regilor Thailandei", "Complex somptuos, cu acoperișuri aurii", "Aflat în Bangkok", ["TEMPLUL AURIU", "TEMPLELE DIN BAGAN", "ANGKOR WAT"]),
    ("MASADA", "Masada fortress Israel", "O fortăreață antică ridicată pe un platou stâncos izolat", "Loc al unui asediu roman celebru din istoria evreiască", "Aflată lângă Marea Moartă, în Israel", ["ZIDUL PLANGERII", "PETRA", "CUPOLA STANCII"]),
]

INSTRUMENTE_ITEMS = [
    ("PIANUL", "Grand piano instrument", "Are 88 de clape, albe și negre", "Sunetul e produs de ciocănele care lovesc corzi", "Instrument folosit atât solo, cât și în orchestră", ["PIANINA", "ORGA", "SINTETIZATORUL"]),
    ("VIOARA", "Violin instrument", "Cel mai mic și mai acut instrument din familia corzilor cu arcuș", "Se cântă cu un arcuș din păr de cal", "Are patru corzi", ["VIOLA", "VIOLONCELUL", "CONTRABASUL"]),
    ("VIOLONCELUL", "Cello instrument", "Se cântă așezat, ținut între genunchi", "Mai mare decât vioara, sunet mai grav", "Are un picioruș metalic ce se sprijină pe podea", ["CONTRABASUL", "VIOARA", "VIOLA"]),
    ("CONTRABASUL", "Double bass instrument", "Cel mai mare și mai grav instrument cu corzi din orchestră", "Se cântă în picioare sau pe un scaun înalt", "Folosit și în muzica clasică, și în jazz", ["VIOLONCELUL", "VIOARA", "HARPA"]),
    ("VIOLA", "Viola instrument", "Puțin mai mare decât vioara, sunet mai cald", "Adesea confundată cu vioara la prima vedere", "Nu are coarda cea mai acută a viorii", ["VIOARA", "VIOLONCELUL", "MANDOLINA"]),
    ("CHITARA ACUSTICA", "Acoustic guitar", "Are o gaură de rezonanță în corpul de lemn", "Nu are nevoie de amplificator electric", "Cel mai popular instrument pentru acompaniat cântece", ["CHITARA ELECTRICA", "CHITARA BAS", "UKULELE"]),
    ("CHITARA ELECTRICA", "Electric guitar", "Sunetul e captat de senzori numiți pickup-uri", "Se conectează la un amplificator", "Instrumentul central al muzicii rock", ["CHITARA ACUSTICA", "CHITARA BAS", "BANJO"]),
    ("CHITARA BAS", "Bass guitar", "Are corzi mai groase, sunet grav", "De obicei doar patru corzi", "Susține ritmul împreună cu tobele", ["CHITARA ELECTRICA", "CONTRABASUL", "CHITARA ACUSTICA"]),
    ("UKULELE", "Ukulele instrument", "Un instrument mic, cu patru corzi", "Originar din Hawaii", "Sunet vesel, foarte popular pentru începători", ["CHITARA ACUSTICA", "BANJO", "MANDOLINA"]),
    ("BANJO", "Banjo instrument", "Are o membrană întinsă, ca a unei tobe, sub corzi", "Sunet caracteristic muzicii country și bluegrass", "Originar din tradițiile africane aduse în America", ["UKULELE", "MANDOLINA", "CHITARA ACUSTICA"]),
    ("MANDOLINA", "Mandolin instrument", "Are corzi grupate în perechi", "Corp rotunjit, ca o pară tăiată", "Foarte folosită în muzica italiană tradițională", ["BANJO", "UKULELE", "VIOARA"]),
    ("HARPA", "Concert harp instrument", "Are zeci de corzi de lungimi diferite", "Se cântă ciupind corzile cu degetele de la ambele mâini", "Unul dintre cele mai vechi instrumente cu corzi din lume", ["CHITARA ACUSTICA", "CONTRABASUL", "PIANUL"]),
    ("FLAUTUL TRAVERSIER", "Flute instrument", "Se ține orizontal și se suflă lateral într-o gaură", "Din familia instrumentelor de suflat din lemn, deși azi e din metal", "Are un sunet clar, ascuțit", ["CLARINETUL", "OBOIUL", "NAIUL"]),
    ("CLARINETUL", "Clarinet instrument", "Are o singură ancie (lamelă) care vibrează", "Corp cilindric, negru, cu clape metalice", "Foarte folosit în jazz și muzică clasică", ["OBOIUL", "SAXOFONUL", "FAGOTUL"]),
    ("OBOIUL", "Oboe instrument", "Are o ancie dublă la capăt", "Sunet pătrunzător, adesea dă tonul orchestrei", "Corp conic, din lemn", ["CLARINETUL", "FAGOTUL", "SAXOFONUL"]),
    ("FAGOTUL", "Bassoon instrument", "Un instrument de suflat lung, îndoit ca un U", "Sunet grav, din familia lemnelor cu ancie dublă", "Unul dintre cele mai mari instrumente de suflat din orchestră", ["OBOIUL", "TUBA", "CORNUL FRANCEZ"]),
    ("SAXOFONUL", "Saxophone instrument", "Făcut din alamă, dar cu ancie ca instrumentele de lemn", "Strâns legat de muzica jazz", "Inventat în secolul XIX de Adolphe Sax", ["CLARINETUL", "TROMPETA", "TROMBONUL"]),
    ("TROMPETA", "Trumpet instrument", "Cel mai acut instrument de alamă", "Are trei pistoane pentru schimbarea notelor", "Foarte folosită în jazz și fanfare", ["TROMBONUL", "CORNUL FRANCEZ", "TUBA"]),
    ("TROMBONUL", "Trombone instrument", "Schimbă notele printr-un culisou care alunecă", "Nu are pistoane ca trompeta", "Sunet puternic, folosit des în fanfare", ["TROMPETA", "TUBA", "CORNUL FRANCEZ"]),
    ("CORNUL FRANCEZ", "French horn instrument", "Tubul foarte lung, încolăcit în spirală", "Mâna dreaptă se ține adesea în interiorul pâlniei", "Sunet cald, folosit des în muzica de film", ["TROMBONUL", "TUBA", "TROMPETA"]),
    ("TUBA", "Tuba instrument", "Cel mai mare și mai grav instrument de alamă", "Se ține de obicei înfășurată în jurul corpului", "Formează baza secțiunii de alămuri din orchestră", ["CORNUL FRANCEZ", "TROMBONUL", "FAGOTUL"]),
    ("TOBA MARE", "Bass drum instrument", "Cea mai mare tobă, cu sunet grav și profund", "Se lovește adesea cu un baros special", "Marchează ritmul de bază în fanfare și orchestre", ["TOBA MICA", "SETUL DE TOBE", "TIMPANUL"]),
    ("TOBA MICA", "Snare drum instrument", "Are corzi metalice întinse pe partea de jos", "Sunet ascuțit, sec, caracteristic", "Piesă centrală a unui set de tobe", ["TOBA MARE", "SETUL DE TOBE", "TAMBURINA"]),
    ("SETUL DE TOBE", "Drum kit instrument", "O combinație de tobe și talere cântate de o singură persoană", "Central în muzica rock, pop și jazz", "Include de obicei toba mare, toba mică și talerele", ["TOBA MARE", "TOBA MICA", "CHIMBALELE"]),
    ("CHIMBALELE", "Cymbals instrument", "Două discuri metalice lovite unul de altul", "Produc un sunet metalic, strălucitor", "Fac parte dintr-un set de tobe sau dintr-o orchestră", ["TOBA MICA", "GONGUL", "SETUL DE TOBE"]),
    ("XILOFONUL", "Xylophone instrument", "Are bare de lemn lovite cu ciocănele", "Fiecare bară produce o notă diferită", "Sunet clar, ascuțit, plăcut copiilor", ["MARIMBA", "VIBRAFONUL", "TAMBALUL"]),
    ("MARIMBA", "Marimba instrument", "Similară xilofonului, dar cu sunet mai cald și mai grav", "Barele sunt din lemn, cu rezonatoare dedesubt", "Originară din Africa și America Centrală", ["XILOFONUL", "VIBRAFONUL", "TAMBALUL"]),
    ("VIBRAFONUL", "Vibraphone instrument", "Are bare metalice, nu de lemn", "Un motor electric îi dă efectul de vibrație", "Foarte folosit în jazz", ["XILOFONUL", "MARIMBA", "CHIMBALELE"]),
    ("TAMBURINA", "Tambourine instrument", "Un cerc cu zurgălăi metalici pe margine", "Se scutură sau se lovește cu palma", "Adesea folosită pentru a marca ritmul în cântece populare", ["MARACASELE", "CASTANIETELE", "TOBA MICA"]),
    ("MARACASELE", "Maracas instrument", "Vin de obicei în pereche, câte una în fiecare mână", "Umplute cu semințe sau bile mici care zornăie", "Instrument tradițional din America Latină", ["TAMBURINA", "CASTANIETELE", "CONGAS"]),
    ("CONGAS", "Conga drum instrument", "Tobe înalte, cilindrice, cântate cu palmele", "Originare din Cuba", "De obicei se cântă în pereche sau grup de trei", ["BONGO", "DJEMBE", "TOBA MARE"]),
    ("BONGO", "Bongo drums instrument", "Două tobe mici, unite între ele", "Se cântă cu degetele și palmele, așezate între genunchi", "Foarte folosite în muzica latino", ["CONGAS", "DJEMBE", "TAMBURINA"]),
    ("DJEMBE", "Djembe drum instrument", "O tobă în formă de cupă, originară din Africa de Vest", "Se cântă cu mâinile goale", "Corpul e sculptat dintr-o singură bucată de lemn", ["CONGAS", "BONGO", "TOBA MARE"]),
    ("ACORDEONUL", "Accordion instrument", "Are o burduf care se întinde și se strânge", "Combină clape sau butoane cu foale de aer", "Foarte folosit în muzica populară și de petrecere", ["ORGA", "MUZICUTA", "CIMPOIUL"]),
    ("ORGA", "Pipe organ instrument", "Poate avea mii de țevi de diferite mărimi", "Aerul e împins prin țevi pentru a produce sunetul", "Instrument tradițional al bisericilor", ["ACORDEONUL", "PIANUL", "PIANINA"]),
    ("PIANINA", "Upright piano instrument", "Versiune verticală a pianului, ocupă mai puțin loc", "Corzile sunt așezate vertical, nu orizontal", "Foarte des întâlnită în casele oamenilor", ["PIANUL", "ORGA", "SINTETIZATORUL"]),
    ("SINTETIZATORUL", "Synthesizer keyboard instrument", "Generează sunete electronic, nu mecanic", "Poate imita alte instrumente sau crea sunete noi", "Esențial în muzica electronică modernă", ["PIANINA", "ORGA", "PIANUL"]),
    ("CIMPOIUL", "Bagpipes instrument", "Aer stocat într-un burduf din piele, apoi împins prin țevi", "Puternic asociat cu tradiția scoțiană", "Sunetul e continuu, fără pauze pentru respirat", ["ACORDEONUL", "DIDGERIDOO", "CORNUL ALPIN"]),
    ("TAMBALUL", "Cimbalom instrument", "Corzi întinse pe o cutie de rezonanță, lovite cu ciocănele", "Foarte prezent în muzica populară din România și Ungaria", "Se cântă așezat, cu instrumentul în față", ["XILOFONUL", "MARIMBA", "HARPA"]),
    ("SITARUL", "Sitar instrument", "Instrument cu coarde, originar din India", "Are un gât lung și un corp mare, rotunjit", "Sunet vibrant, cu corzi de rezonanță suplimentare", ["MANDOLINA", "BANJO", "COBZA"]),
    ("DIDGERIDOO", "Didgeridoo instrument", "Un tub lung de lemn, din tradiția aborigenă australiană", "Se cântă cu tehnica respirației circulare", "Produce un sunet continuu, vibrant, grav", ["CORNUL ALPIN", "CIMPOIUL", "TUBA"]),
    ("KALIMBA", "Kalimba instrument", "Lamele metalice ciupite cu degetele mari", "Numit și 'pianul degetelor mari'", "Originar din Africa", ["XILOFONUL", "MARIMBA", "TAMBALUL"]),
    ("CASTANIETELE", "Castanets instrument", "Două scoici mici, lovite una de alta", "Strâns legate de dansul flamenco", "Se țin în palmă și se lovesc cu degetele", ["MARACASELE", "TAMBURINA", "CHIMBALELE"]),
    ("TRIUNGHIUL", "Triangle musical instrument", "O bară metalică îndoită în formă de triunghi", "Se lovește cu o baghetă metalică subțire", "Unul dintre cele mai simple instrumente de percuție", ["CHIMBALELE", "GONGUL", "TAMBURINA"]),
    ("MUZICUTA", "Harmonica instrument", "Mică, se ține în palmă și se suflă în ea", "Foarte folosită în muzica blues și country", "Are camere mici cu lamele metalice în interior", ["ACORDEONUL", "CIMPOIUL", "NAIUL"]),
    ("CORNUL ALPIN", "Alphorn instrument", "Foarte lung, din lemn, fără găuri sau clape", "Tradițional în zonele muntoase din Elveția", "Notele se schimbă doar prin poziția buzelor", ["DIDGERIDOO", "TUBA", "CORNUL FRANCEZ"]),
    ("BALALAICA", "Balalaika instrument", "Are corp triunghiular și de obicei trei corzi", "Instrument tradițional rusesc", "Vine în mai multe mărimi, de la mic la contrabas", ["MANDOLINA", "SITARUL", "COBZA"]),
    ("FLUIERUL", "Tin whistle instrument", "Un tub simplu, cu găuri, cântat din tradiția populară", "Asociat cu ciobanii din zonele de munte", "Unul dintre cele mai vechi instrumente de suflat", ["NAIUL", "FLAUTUL TRAVERSIER", "CORNUL ALPIN"]),
    ("NAIUL", "Pan flute instrument", "Format din mai multe țevi de lungimi diferite, legate între ele", "Fiecare țeavă produce o notă diferită", "Instrument tradițional în muzica populară românească", ["FLUIERUL", "FLAUTUL TRAVERSIER", "CORNUL ALPIN"]),
    ("GONGUL", "Gong instrument", "Un disc metalic mare, suspendat, lovit cu un ciocan moale", "Sunetul vibrează și se stinge lent", "Originar din Asia, folosit și în ceremonii", ["CHIMBALELE", "TRIUNGHIUL", "TOBA MARE"]),
    ("COBZA", "Cobza instrument", "Instrument tradițional românesc cu coarde, fără taste", "Corp în formă de pară, ca o lăută", "Folosit des în muzica lăutărească", ["MANDOLINA", "BALALAICA", "SITARUL"]),
    ("CHARANGO", "Charango instrument", "Un instrument mic cu corzi, din America de Sud", "Corpul era tradițional făcut din carapace de armadillo", "Sunet ascuțit, folosit în muzica andină", ["UKULELE", "MANDOLINA", "BANJO"]),
    ("BANDONEON", "Bandoneon instrument", "O variantă de acordeon, esențială în muzica de tango", "Se ține în poală și se întinde ca un burduf", "Strâns asociat cu tango-ul argentinian", ["ACORDEONUL", "ORGA", "MUZICUTA"]),
    ("ERHU", "Erhu Chinese instrument", "Are doar două corzi, cântate cu un arcuș", "Instrument tradițional chinezesc", "Sunet asemănător vocii umane, foarte expresiv", ["VIOARA", "SITARUL", "COBZA"]),
    ("KOTO", "Koto Japanese instrument", "Un instrument lung, cu corzi întinse peste piese mobile", "Instrument tradițional japonez", "Se cântă așezat pe podea, ciupind corzile", ["HARPA", "SITARUL", "TAMBALUL"]),
    ("VIELEA CU ROATA", "Hurdy-gurdy instrument", "O roată învârtită cu o manivelă freacă niște corzi", "Instrument medieval european, cu sunet continuu", "Are și taste pentru schimbarea notelor", ["CIMPOIUL", "ACORDEONUL", "VIOARA"]),
    ("GOARNA", "Bugle instrument", "Un instrument de alamă simplu, fără pistoane sau clape", "Folosit tradițional în armată, pentru semnale", "Notele se schimbă doar prin poziția buzelor", ["TROMPETA", "CORNUL FRANCEZ", "CORNUL ALPIN"]),
    ("PICCOLO", "Piccolo flute instrument", "Cel mai mic și mai acut instrument din familia flautelor", "Jumătate din mărimea unui flaut obișnuit", "Foarte folosit în fanfare militare", ["FLAUTUL TRAVERSIER", "CLARINETUL", "NAIUL"]),
    ("CORNUL ENGLEZESC", "English horn instrument", "Mai mare decât oboiul, sunet mai grav și mai cald", "Are o formă de pară în capătul pâlniei", "Face parte din familia instrumentelor cu ancie dublă", ["OBOIUL", "FAGOTUL", "CLARINETUL"]),
    ("SOUSAFONUL", "Sousaphone instrument", "O tubă mare, curbată să se poarte în jurul corpului", "Folosită mai ales în fanfare care merg în marș", "Pâlnia uriașă e orientată înainte, deasupra capului", ["TUBA", "CORNUL FRANCEZ", "TROMBONUL"]),
    ("TOBA DE OTEL", "Steel drum instrument", "Făcută dintr-un butoi metalic gol, cu zone marcate ce dau note diferite", "Originară din Trinidad și Tobago", "Sunet metalic, vesel, asociat cu muzica din Caraibe", ["CONGAS", "GONGUL", "XILOFONUL"]),
]

# id_prefix, culoare_tema, descriere, imagine_sursa (toate "custom" prin
# imagine_cautare), ITEMS.
CATEGORII = {
    "steaguri": dict(prefix="stg", culoare="#1FA2B8", descriere="Steaguri și țări", items=STEAGURI_ITEMS),
    "animale": dict(prefix="ani", culoare="#27AE60", descriere="Animale din toată lumea", items=ANIMALE_ITEMS),
    "monumente": dict(prefix="mon", culoare="#B8860B", descriere="Monumente și minuni ale lumii", items=MONUMENTE_ITEMS),
    "instrumente": dict(prefix="ins", culoare="#D63384", descriere="Instrumente muzicale", items=INSTRUMENTE_ITEMS),
}


def build(categorie_id):
    cfg = CATEGORII[categorie_id]
    intrebari = []
    for i, (answer, search, h1, h2, h3, wrongs) in enumerate(cfg["items"], start=1):
        intrebari.append({
            "id": f"{cfg['prefix']}_{i:03d}",
            "raspuns": answer,
            "variante": [answer] + wrongs,
            "hint_1": h1,
            "hint_2": h2,
            "hint_3": h3,
            "dificultate": "usor" if i <= len(cfg["items"]) // 2 else "mediu",
            "puncte_max": 200,
            "imagine_cautare": search,
            "imagine_sursa": "wikimedia",
        })

    data = {"categorii": {categorie_id: {
        "mod": "4_variante",
        "culoare_tema": cfg["culoare"],
        "descriere": cfg["descriere"],
        "intrebari": intrebari,
    }}}

    out = f"assets/continut/{categorie_id}/intrebari.json"
    with open(out, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Scris {out} cu {len(intrebari)} intrebari")

    answers = [it[0] for it in cfg["items"]]
    dupes = {a for a in answers if answers.count(a) > 1}
    if dupes:
        print(f"ATENTIE [{categorie_id}], raspunsuri duplicate:", dupes)


def main():
    targets = sys.argv[1:] or list(CATEGORII)
    for categorie_id in targets:
        build(categorie_id)


if __name__ == "__main__":
    main()
