name: guess_it
description: "Ghicește ce se ascunde în poza neclară. 14 categorii și multiplayer live."
publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ^3.6.2

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  google_sign_in: ^7.1.1
  http: ^1.6.0
  google_mobile_ads: ^5.3.1
  firebase_auth_games_services: ^3.0.1
  firebase_app_check: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/continut/cartoon/
    - assets/continut/cartoon/poze/
    - assets/continut/logouri/
    - assets/continut/logouri/poze/
    - assets/continut/jocuri/
    - assets/continut/jocuri/poze/
    - assets/continut/medical/
    - assets/continut/medical/poze/
    - assets/continut/mecanica/
    - assets/continut/mecanica/poze/
    - assets/continut/aplicatii/
    - assets/continut/aplicatii/poze/
    - assets/continut/masini/
    - assets/continut/masini/poze/
    - assets/continut/celebritati/
    - assets/continut/celebritati/poze/
    - assets/continut/sport/
    - assets/continut/sport/poze/
    - assets/continut/romania/
    - assets/continut/romania/poze/
    - assets/continut/steaguri/
    - assets/continut/steaguri/poze/
    - assets/continut/animale/
    - assets/continut/animale/poze/
    - assets/continut/monumente/
    - assets/continut/monumente/poze/
    - assets/continut/instrumente/
    - assets/continut/instrumente/poze/
    - assets/sfx/
    - assets/music/