"""Genereaza intrebari.json pentru cele 4 gamemoduri premium din shop:
masini (Masini de Lux), celebritati, sport (Fotbal & Sport), romania.

50 de intrebari per mod (cat promite shop-ul: "intrebari": 50), format identic
cu mecanica/medical: 4 variante, 3 hinturi, dificultate, imagine_cautare
(termen EN pentru Wikipedia — folosit de tools/fetch_question_images.py).

Rulare: python tools/generate_premium_questions.py
"""
import json
import os

PUNCTE = {"usor": 200, "mediu": 400, "greu": 600}

# (raspuns, [3 variante gresite], hint_1, hint_2, hint_3, dificultate, imagine_cautare)
MASINI = [
    ("FERRARI", ["LAMBORGHINI", "MASERATI", "ALFA ROMEO"], "Cal cabrat negru pe siglă", "Fondată de Enzo în 1939", "Bolizi roșii din Maranello", "usor", "Ferrari"),
    ("LAMBORGHINI", ["FERRARI", "BUGATTI", "MCLAREN"], "Taur auriu pe siglă", "Fondatorul făcea tractoare la început", "Aventador și Huracán", "usor", "Lamborghini"),
    ("PORSCHE", ["AUDI", "BMW", "MERCEDES"], "Siglă cu cal negru, din Stuttgart", "Celebrul model 911", "Marcă germană de mașini sport", "usor", "Porsche"),
    ("BUGATTI", ["KOENIGSEGG", "PAGANI", "MCLAREN"], "Marcă franceză de hypercar-uri", "Veyron și Chiron", "Peste 400 km/h viteză maximă", "mediu", "Bugatti"),
    ("ROLLS ROYCE", ["BENTLEY", "MAYBACH", "JAGUAR"], "Statueta Spirit of Ecstasy pe capotă", "Simbol al luxului britanic", "Phantom și Ghost", "usor", "Rolls-Royce Motor Cars"),
    ("BENTLEY", ["ROLLS ROYCE", "ASTON MARTIN", "JAGUAR"], "Litera B cu aripi pe siglă", "Lux britanic din Crewe", "Continental GT", "mediu", "Bentley Continental GT"),
    ("ASTON MARTIN", ["JAGUAR", "BENTLEY", "MASERATI"], "Mașina lui James Bond", "Aripi întinse pe siglă", "DB11 și Vantage", "mediu", "Aston Martin DB11"),
    ("MASERATI", ["ALFA ROMEO", "FERRARI", "LANCIA"], "Trident pe siglă", "Marcă italiană din Modena", "GranTurismo și Levante", "mediu", "Maserati GranTurismo"),
    ("MCLAREN", ["FERRARI", "PORSCHE", "LOTUS"], "Marcă britanică cu echipă de Formula 1", "Sigla portocalie tip 'swoosh'", "720S și P1", "mediu", "McLaren 720S"),
    ("KOENIGSEGG", ["PAGANI", "BUGATTI", "RIMAC"], "Hypercar-uri suedeze", "Fondată de Christian von Koenigsegg", "Agera și Jesko", "greu", "Koenigsegg Agera"),
    ("PAGANI", ["KOENIGSEGG", "BUGATTI", "LAMBORGHINI"], "Hypercar italian fondat de un argentinian", "Zonda și Huayra", "Caroserii din carbon lucrate manual", "greu", "Pagani Huayra"),
    ("FERRARI F40", ["FERRARI TESTAROSSA", "LAMBORGHINI COUNTACH", "PORSCHE 959"], "Ultima mașină aprobată de Enzo Ferrari", "Lansată în 1987", "Legendă cu eleron uriaș", "greu", "Ferrari F40"),
    ("LAMBORGHINI AVENTADOR", ["LAMBORGHINI HURACAN", "FERRARI 488", "MCLAREN 720S"], "V12 italian cu uși care se deschid în sus", "Poartă numele unui taur de luptă", "Flagship-ul cu peste 700 CP", "mediu", "Lamborghini Aventador"),
    ("LAMBORGHINI URUS", ["PORSCHE CAYENNE", "BENTLEY BENTAYGA", "AUDI Q8"], "SUV-ul super-sport italian", "Taurul de teren al mărcii", "SUV cu peste 650 CP", "usor", "Lamborghini Urus"),
    ("PORSCHE 911", ["PORSCHE CAYMAN", "NISSAN GTR", "AUDI R8"], "Silueta neschimbată din 1963", "Motorul e în spate", "Cel mai cunoscut model al mărcii", "usor", "Porsche 911"),
    ("MERCEDES G CLASS", ["RANGE ROVER", "JEEP WRANGLER", "TOYOTA LAND CRUISER"], "Cutia pătrată de lux germană", "Poreclit 'Gelandewagen'", "Off-roaderul favorit al vedetelor", "usor", "Mercedes-Benz G-Class"),
    ("MERCEDES AMG GT", ["PORSCHE 911", "BMW M8", "AUDI R8"], "Coupe sport cu stea pe grilă", "Rival direct pentru 911", "Construit la Affalterbach", "mediu", "Mercedes-AMG GT"),
    ("BMW M3", ["BMW M5", "AUDI RS4", "MERCEDES C63"], "Sedanul sport bavarez legendar", "Litera M vine de la Motorsport", "Bazat pe Seria 3", "usor", "BMW M3"),
    ("BMW I8", ["AUDI R8", "HONDA NSX", "TESLA ROADSTER"], "Sportivă hibridă cu uși fluture", "Design futurist lansat în 2014", "Consum mic, aspect de supercar", "mediu", "BMW i8"),
    ("AUDI R8", ["LAMBORGHINI HURACAN", "PORSCHE 911", "NISSAN GTR"], "Supercarul cu patru inele", "Împarte motorul V10 cu Huracán", "Mașina lui Iron Man", "usor", "Audi R8"),
    ("TESLA MODEL S", ["TESLA MODEL 3", "PORSCHE TAYCAN", "LUCID AIR"], "Sedanul electric american de lux", "Modul 'Ludicrous' de accelerație", "Fabricat de compania lui Elon Musk", "usor", "Tesla Model S"),
    ("TESLA CYBERTRUCK", ["HUMMER EV", "RIVIAN R1T", "FORD F150"], "Camionetă electrică unghiulară", "Caroserie din oțel inoxidabil", "Geamurile 'incasabile' s-au spart la prezentare", "usor", "Tesla Cybertruck"),
    ("DODGE VIPER", ["CHEVROLET CORVETTE", "FORD GT", "SHELBY COBRA"], "Șarpele american cu motor V10", "Produs între 1991 și 2017", "Muscle car extrem din Detroit", "mediu", "Dodge Viper"),
    ("CHEVROLET CORVETTE", ["DODGE VIPER", "FORD MUSTANG", "CHEVROLET CAMARO"], "Sportiva americană emblemă din 1953", "Poreclită 'Vette'", "Generația C8 are motor central", "mediu", "Chevrolet Corvette"),
    ("FORD MUSTANG", ["CHEVROLET CAMARO", "DODGE CHALLENGER", "FORD GT"], "Pony car cu cal în galop pe grilă", "Lansat în 1964", "Cel mai cunoscut muscle car american", "usor", "Ford Mustang"),
    ("NISSAN GTR", ["TOYOTA SUPRA", "MAZDA RX7", "HONDA NSX"], "Poreclit 'Godzilla'", "Legendă japoneză cu tracțiune integrală", "Celebru din Fast & Furious", "mediu", "Nissan GT-R"),
    ("TOYOTA SUPRA", ["NISSAN GTR", "MAZDA RX7", "HONDA NSX"], "Legenda japoneză cu motor 2JZ", "Mașina portocalie din primul Fast & Furious", "Relansată în 2019 cu ajutor de la BMW", "mediu", "Toyota Supra"),
    ("JAGUAR F TYPE", ["ASTON MARTIN VANTAGE", "PORSCHE 911", "BMW Z4"], "Sportiva britanică cu felină pe siglă", "Urmașul spiritual al lui E-Type", "Sunet celebru de eșapament", "greu", "Jaguar F-Type"),
    ("BUGATTI VEYRON", ["BUGATTI CHIRON", "KOENIGSEGG CCX", "MCLAREN F1"], "Primul model de serie cu 1001 CP", "Record mondial de viteză în 2005", "Motor W16 cu 4 turbine", "usor", "Bugatti Veyron"),
    ("BUGATTI CHIRON", ["BUGATTI VEYRON", "KOENIGSEGG JESKO", "PAGANI HUAYRA"], "Urmașul lui Veyron", "1500 CP din fabrică", "A depășit 490 km/h în 2019", "mediu", "Bugatti Chiron"),
    ("FERRARI LAFERRARI", ["MCLAREN P1", "PORSCHE 918", "FERRARI ENZO"], "Hibridul hypercar din Maranello", "Numele înseamnă chiar 'Ferrari-ul'", "Face parte din 'sfânta treime' cu P1 și 918", "greu", "LaFerrari"),
    ("PORSCHE PANAMERA", ["PORSCHE TAYCAN", "AUDI A7", "MERCEDES CLS"], "Sedanul cu 4 uși de la Stuttgart", "Numele vine de la cursa Carrera Panamericana", "Fratele practic al lui 911", "mediu", "Porsche Panamera"),
    ("LAMBORGHINI HURACAN", ["LAMBORGHINI AVENTADOR", "FERRARI 488", "AUDI R8"], "V10 italian, fratele mai mic al Aventadorului", "Numit după un taur celebru din 1879", "A înlocuit modelul Gallardo", "mediu", "Lamborghini Huracán"),
    ("ROLLS ROYCE CULLINAN", ["BENTLEY BENTAYGA", "LAMBORGHINI URUS", "RANGE ROVER"], "Primul SUV Rolls-Royce", "Numit după cel mai mare diamant descoperit", "Lux suprem la înălțime", "greu", "Rolls-Royce Cullinan"),
    ("BENTLEY BENTAYGA", ["ROLLS ROYCE CULLINAN", "LAMBORGHINI URUS", "PORSCHE CAYENNE"], "SUV-ul de lux din Crewe", "Numit după un vârf muntos din Canare", "Interior din lemn și piele lucrat manual", "greu", "Bentley Bentayga"),
    ("MCLAREN P1", ["FERRARI LAFERRARI", "PORSCHE 918", "MCLAREN 720S"], "Hibridul hypercar britanic", "916 CP, doar 375 de bucăți", "Parte din 'sfânta treime' hypercar", "greu", "McLaren P1"),
    ("PORSCHE TAYCAN", ["TESLA MODEL S", "AUDI E-TRON GT", "PORSCHE PANAMERA"], "Primul Porsche complet electric", "Numele înseamnă 'mânz vioi'", "Rivalul german al Teslei", "mediu", "Porsche Taycan"),
    ("AUDI RS6", ["BMW M5", "MERCEDES E63", "AUDI RS4"], "Break-ul german de 600 CP", "Combină familia cu circuitul", "Avant — cel mai faimos break sport", "mediu", "Audi RS 6"),
    ("MERCEDES SLS AMG", ["MERCEDES AMG GT", "BMW I8", "AUDI R8"], "Uși 'gullwing', ca aripile unui pescăruș", "Omagiu pentru 300 SL din anii '50", "V8 de 6.2 litri atmosferic", "greu", "Mercedes-Benz SLS AMG"),
    ("FERRARI 488", ["FERRARI F8", "LAMBORGHINI HURACAN", "MCLAREN 720S"], "V8 biturbo cu motor central", "A înlocuit modelul 458", "Versiunile GTB și Spider", "greu", "Ferrari 488"),
    ("LAMBORGHINI GALLARDO", ["LAMBORGHINI MURCIELAGO", "FERRARI F430", "AUDI R8"], "Cel mai vândut Lambo al anilor 2000", "Predecesorul lui Huracán", "V10 din Sant'Agata", "mediu", "Lamborghini Gallardo"),
    ("FORD GT", ["FORD MUSTANG", "CHEVROLET CORVETTE", "DODGE VIPER"], "Supercarul american născut să bată Ferrari", "Omagiu pentru GT40 de la Le Mans", "Filmul 'Ford v Ferrari' îi spune povestea", "greu", "Ford GT"),
    ("HONDA NSX", ["TOYOTA SUPRA", "NISSAN GTR", "MAZDA RX7"], "Supercarul japonez dezvoltat cu Ayrton Senna", "'Ferrari-ul de zi cu zi'", "Vândut ca Acura în America", "greu", "Honda NSX"),
    ("LEXUS LFA", ["HONDA NSX", "NISSAN GTR", "TOYOTA SUPRA"], "V10 japonez cu sunet legendar", "Doar 500 de bucăți produse", "Vine de la divizia de lux Toyota", "greu", "Lexus LFA"),
    ("ALFA ROMEO GIULIA", ["BMW M3", "MASERATI GHIBLI", "AUDI S4"], "Sedan sport italian cu trifoi verde", "Versiunea Quadrifoglio are motor derivat din Ferrari", "Marcă din Milano cu șarpe pe siglă", "mediu", "Alfa Romeo Giulia (952)"),
    ("PORSCHE CAYENNE", ["LAMBORGHINI URUS", "BMW X5", "AUDI Q7"], "SUV-ul care a salvat marca", "Lansat în 2002", "Fratele de teren al lui 911", "usor", "Porsche Cayenne"),
    ("RANGE ROVER", ["MERCEDES G CLASS", "BMW X7", "VOLVO XC90"], "SUV-ul britanic regal", "Produs de Land Rover", "Favoritul familiei regale britanice", "usor", "Range Rover"),
    ("FERRARI ENZO", ["FERRARI LAFERRARI", "FERRARI F40", "PAGANI ZONDA"], "Poartă numele fondatorului", "Tehnologie de Formula 1 din 2002", "Doar 400 de exemplare", "greu", "Enzo Ferrari (automobile)"),
    ("MAYBACH", ["ROLLS ROYCE", "BENTLEY", "LINCOLN"], "Divizia ultra-lux Mercedes", "Limuzine cu șofer prin excelență", "57 și 62 au fost modelele clasice", "greu", "Maybach"),
    ("ROLLS ROYCE PHANTOM", ["ROLLS ROYCE GHOST", "BENTLEY MULSANNE", "MAYBACH 62"], "Limuzina supremă britanică", "Umbrele ascunse în uși", "Flagship-ul cu Spirit of Ecstasy", "mediu", "Rolls-Royce Phantom VIII"),
]

CELEBRITATI = [
    ("LEONARDO DICAPRIO", ["BRAD PITT", "JOHNNY DEPP", "MATT DAMON"], "Actorul din Titanic", "Oscar pentru The Revenant", "Colaborări celebre cu Scorsese și Tarantino", "usor", "Leonardo DiCaprio"),
    ("BRAD PITT", ["GEORGE CLOONEY", "TOM CRUISE", "LEONARDO DICAPRIO"], "Actorul din Fight Club", "Fost soț al Angelinei Jolie", "Oscar pentru Once Upon a Time in Hollywood", "usor", "Brad Pitt"),
    ("ANGELINA JOLIE", ["JENNIFER ANISTON", "MONICA BELLUCCI", "CHARLIZE THERON"], "Actrița din Maleficent", "Lara Croft în Tomb Raider", "Ambasadoare a bunăvoinței la ONU", "usor", "Angelina Jolie"),
    ("TOM CRUISE", ["TOM HANKS", "BRAD PITT", "KEANU REEVES"], "Își face singur cascadoriile", "Seria Mission: Impossible", "Pilotul din Top Gun", "usor", "Tom Cruise"),
    ("JOHNNY DEPP", ["ORLANDO BLOOM", "ROBERT DOWNEY JR", "JARED LETO"], "Căpitanul Jack Sparrow", "Edward Mâini-de-Foarfecă", "Proces celebru cu Amber Heard", "usor", "Johnny Depp"),
    ("WILL SMITH", ["DENZEL WASHINGTON", "KEVIN HART", "JAMIE FOXX"], "Prințul din Bel-Air", "Agentul din Men in Black", "Palma de la Oscarurile din 2022", "usor", "Will Smith"),
    ("DWAYNE JOHNSON", ["VIN DIESEL", "JASON STATHAM", "JOHN CENA"], "Poreclit 'The Rock'", "Fost wrestler WWE", "Joacă în Fast & Furious și Jumanji", "usor", "Dwayne Johnson"),
    ("KEANU REEVES", ["HUGH JACKMAN", "CHRISTIAN BALE", "TOM CRUISE"], "Neo din Matrix", "Asasinul John Wick", "Considerat cel mai cumsecade om din Hollywood", "usor", "Keanu Reeves"),
    ("TOM HANKS", ["TOM CRUISE", "ROBIN WILLIAMS", "MORGAN FREEMAN"], "Forrest Gump", "Vocea lui Woody din Toy Story", "Naufragiatul din Cast Away", "usor", "Tom Hanks"),
    ("MORGAN FREEMAN", ["SAMUEL L JACKSON", "DENZEL WASHINGTON", "WILL SMITH"], "Vocea inconfundabilă a documentarelor", "Deținutul Red din Shawshank", "L-a interpretat pe Dumnezeu în comedie", "usor", "Morgan Freeman"),
    ("ROBERT DOWNEY JR", ["CHRIS EVANS", "CHRIS HEMSWORTH", "MARK RUFFALO"], "Iron Man", "Sherlock Holmes în filmele lui Guy Ritchie", "Oscar pentru Oppenheimer", "usor", "Robert Downey Jr."),
    ("SCARLETT JOHANSSON", ["JENNIFER LAWRENCE", "MARGOT ROBBIE", "GAL GADOT"], "Black Widow din Avengers", "Vocea din filmul Her", "Actriță născută la New York", "mediu", "Scarlett Johansson"),
    ("EMMA WATSON", ["EMMA STONE", "NATALIE PORTMAN", "ANNE HATHAWAY"], "Hermione din Harry Potter", "Activistă pentru egalitate de gen", "Belle din Beauty and the Beast", "usor", "Emma Watson"),
    ("JENNIFER LAWRENCE", ["SCARLETT JOHANSSON", "EMMA STONE", "ANNE HATHAWAY"], "Katniss din Hunger Games", "Oscar la doar 22 de ani", "A căzut pe scări la Oscaruri", "mediu", "Jennifer Lawrence"),
    ("RIHANNA", ["BEYONCE", "NICKI MINAJ", "CARDI B"], "Cântăreața din Barbados", "Umbrella și Diamonds", "Fondatoarea Fenty Beauty", "usor", "Rihanna"),
    ("BEYONCE", ["RIHANNA", "ALICIA KEYS", "MARIAH CAREY"], "Poreclită 'Queen B'", "Fostă solistă Destiny's Child", "Soția lui Jay-Z", "usor", "Beyoncé"),
    ("TAYLOR SWIFT", ["SELENA GOMEZ", "ARIANA GRANDE", "KATY PERRY"], "Turneul 'The Eras Tour'", "Shake It Off", "Recorduri absolute la premiile Grammy", "usor", "Taylor Swift"),
    ("ARIANA GRANDE", ["SELENA GOMEZ", "BILLIE EILISH", "DUA LIPA"], "Coada de păr semnătură", "Thank U, Next", "Glinda în filmul Wicked", "usor", "Ariana Grande"),
    ("SELENA GOMEZ", ["ARIANA GRANDE", "DEMI LOVATO", "HAILEY BIEBER"], "Fostă vedetă Disney", "Fondatoarea Rare Beauty", "Serialul Only Murders in the Building", "usor", "Selena Gomez"),
    ("JUSTIN BIEBER", ["SHAWN MENDES", "ZAYN MALIK", "HARRY STYLES"], "Descoperit pe YouTube la 13 ani", "Baby și Sorry", "Canadian căsătorit cu Hailey", "usor", "Justin Bieber"),
    ("ED SHEERAN", ["SAM SMITH", "SHAWN MENDES", "LEWIS CAPALDI"], "Roșcatul cu chitara", "Shape of You", "Cântăreț britanic plin de tatuaje", "usor", "Ed Sheeran"),
    ("ADELE", ["CELINE DION", "LADY GAGA", "DUA LIPA"], "Voce puternică din Londra", "Hello și Rolling in the Deep", "Albume numite după vârsta ei", "usor", "Adele"),
    ("DUA LIPA", ["ARIANA GRANDE", "RITA ORA", "BILLIE EILISH"], "Cântăreață britanică cu origini albaneze", "Levitating", "New Rules", "mediu", "Dua Lipa"),
    ("SHAKIRA", ["JENNIFER LOPEZ", "RIHANNA", "BEYONCE"], "'Șoldurile nu mint'", "Cântăreață columbiană", "Waka Waka, imnul Cupei Mondiale", "usor", "Shakira"),
    ("JENNIFER LOPEZ", ["SHAKIRA", "BEYONCE", "CARDI B"], "J.Lo din Bronx", "On the Floor", "Relația celebră cu Ben Affleck", "mediu", "Jennifer Lopez"),
    ("LADY GAGA", ["MADONNA", "KATY PERRY", "BILLIE EILISH"], "Rochia din carne", "Poker Face", "Oscar pentru piesa Shallow", "usor", "Lady Gaga"),
    ("MADONNA", ["LADY GAGA", "CHER", "BRITNEY SPEARS"], "Regina muzicii pop", "Like a Prayer", "Carieră de peste 40 de ani", "mediu", "Madonna"),
    ("EMINEM", ["DRAKE", "SNOOP DOGG", "50 CENT"], "Alter ego-ul Slim Shady", "Rapper din Detroit", "Lose Yourself", "usor", "Eminem"),
    ("DRAKE", ["EMINEM", "KANYE WEST", "THE WEEKND"], "Rapper din Toronto", "God's Plan", "Rivalitatea celebră cu Kendrick Lamar", "mediu", "Drake (musician)"),
    ("SNOOP DOGG", ["EMINEM", "50 CENT", "ICE CUBE"], "Rapper din Long Beach", "Prieten cu Martha Stewart", "Stil relaxat West Coast", "mediu", "Snoop Dogg"),
    ("KANYE WEST", ["DRAKE", "JAY Z", "TRAVIS SCOTT"], "Fost soț al lui Kim Kardashian", "Brandul de adidași Yeezy", "S-a redenumit Ye", "mediu", "Kanye West"),
    ("KIM KARDASHIAN", ["KYLIE JENNER", "PARIS HILTON", "BEYONCE"], "Vedetă de reality show", "Brandul SKIMS", "Cea mai cunoscută familie de surori din TV", "usor", "Kim Kardashian"),
    ("ELON MUSK", ["JEFF BEZOS", "MARK ZUCKERBERG", "BILL GATES"], "Șeful Tesla și SpaceX", "A cumpărat Twitter și l-a redenumit X", "Printre cei mai bogați oameni ai planetei", "usor", "Elon Musk"),
    ("BILL GATES", ["STEVE JOBS", "ELON MUSK", "MARK ZUCKERBERG"], "Fondatorul Microsoft", "Filantrop miliardar", "A creat sistemul Windows", "usor", "Bill Gates"),
    ("MARK ZUCKERBERG", ["ELON MUSK", "JEFF BEZOS", "JACK DORSEY"], "Fondatorul Facebook", "A pornit rețeaua din camera de cămin", "Șeful companiei Meta", "usor", "Mark Zuckerberg"),
    ("JEFF BEZOS", ["ELON MUSK", "BILL GATES", "WARREN BUFFETT"], "Fondatorul Amazon", "Zboruri spațiale cu Blue Origin", "A început cu o librărie online", "mediu", "Jeff Bezos"),
    ("OPRAH WINFREY", ["ELLEN DEGENERES", "MICHELLE OBAMA", "WHOOPI GOLDBERG"], "Regina talk-show-urilor", "'You get a car!'", "Miliardară din televiziune", "mediu", "Oprah Winfrey"),
    ("MRBEAST", ["PEWDIEPIE", "LOGAN PAUL", "KSI"], "Cel mai urmărit YouTuber din lume", "Provocări cu premii uriașe în bani", "Jimmy Donaldson pe numele real", "usor", "MrBeast"),
    ("ZENDAYA", ["BILLIE EILISH", "SELENA GOMEZ", "MILEY CYRUS"], "MJ din filmele Spider-Man", "Serialul Euphoria", "Joacă în filmele Dune", "mediu", "Zendaya"),
    ("BILLIE EILISH", ["ARIANA GRANDE", "DUA LIPA", "OLIVIA RODRIGO"], "Bad Guy", "Stilul șoptit și părul verde-negru", "Fratele Finneas îi produce piesele", "usor", "Billie Eilish"),
    ("THE WEEKND", ["DRAKE", "BRUNO MARS", "POST MALONE"], "Blinding Lights", "Canadian de origine etiopiană", "Abel Tesfaye pe numele real", "mediu", "The Weeknd"),
    ("BRUNO MARS", ["THE WEEKND", "JUSTIN TIMBERLAKE", "USHER"], "Uptown Funk", "Cântăreț născut în Hawaii", "24K Magic", "mediu", "Bruno Mars"),
    ("KATY PERRY", ["LADY GAGA", "TAYLOR SWIFT", "MILEY CYRUS"], "Firework", "Jurată la American Idol", "Roar", "mediu", "Katy Perry"),
    ("MILEY CYRUS", ["SELENA GOMEZ", "DEMI LOVATO", "KATY PERRY"], "Fosta Hannah Montana", "Wrecking Ball", "Grammy pentru piesa Flowers", "usor", "Miley Cyrus"),
    ("HARRY STYLES", ["JUSTIN BIEBER", "SHAWN MENDES", "ZAYN MALIK"], "Fost membru One Direction", "Watermelon Sugar", "Stil vestimentar excentric", "mediu", "Harry Styles"),
    ("INNA", ["DELIA", "ANDRA", "ALEXANDRA STAN"], "Românca cu hituri ascultate global", "Hot și Sun Is Up", "Printre cele mai ascultate artiste române din lume", "usor", "Inna"),
    ("SMILEY", ["ALEX VELEA", "RANDI", "MARIUS MOGA"], "Jurat la Vocea României", "Hitul 'Acasă'", "Andrei Maria pe numele real", "usor", "Smiley (singer)"),
    ("DELIA", ["INNA", "ANDRA", "LOREDANA"], "Jurată la iUmor", "Fostă solistă N&D", "Părul mereu în culori neon", "usor", "Delia Matache"),
    ("ANDRA", ["DELIA", "INNA", "ELENA GHEORGHE"], "Jurată la Românii au Talent", "Căsătorită cu Cătălin Măruță", "A început în copilărie cu muzică populară", "mediu", "Andra (singer)"),
    ("ANDREEA ESCA", ["MIHAELA RADULESCU", "SIMONA GHERGHE", "TEO TRANDAFIR"], "Prezentatoarea Știrilor PRO TV", "Peste 25 de ani la pupitrul știrilor", "Cel mai cunoscut chip din televiziunea română", "mediu", "Andreea Esca"),
]

SPORT = [
    ("LIONEL MESSI", ["CRISTIANO RONALDO", "NEYMAR", "LUIS SUAREZ"], "8 Baloane de Aur", "Campion mondial cu Argentina în 2022", "Legenda Barcelonei", "usor", "Lionel Messi"),
    ("CRISTIANO RONALDO", ["LIONEL MESSI", "KAKA", "ZLATAN IBRAHIMOVIC"], "CR7", "Celebrarea 'Siuuu'", "Golgheterul all-time al fotbalului", "usor", "Cristiano Ronaldo"),
    ("NEYMAR", ["VINICIUS JUNIOR", "RONALDINHO", "KYLIAN MBAPPE"], "Starul brazilian al driblingurilor", "Transferul record la PSG", "Numărul 10 al Braziliei", "usor", "Neymar"),
    ("KYLIAN MBAPPE", ["ERLING HAALAND", "NEYMAR", "ANTOINE GRIEZMANN"], "Rapidul atacant francez", "Campion mondial la 19 ani", "Transferat la Real Madrid în 2024", "usor", "Kylian Mbappé"),
    ("ERLING HAALAND", ["KYLIAN MBAPPE", "HARRY KANE", "ROBERT LEWANDOWSKI"], "Vikingul golgheter", "Mașina de goluri de la Manchester City", "Norvegian cu fizic de robot", "usor", "Erling Haaland"),
    ("MOHAMED SALAH", ["SADIO MANE", "RIYAD MAHREZ", "KARIM BENZEMA"], "'Faraonul egiptean'", "Legenda lui Liverpool", "Golgheter în repetate rânduri în Premier League", "mediu", "Mohamed Salah"),
    ("ROBERT LEWANDOWSKI", ["ERLING HAALAND", "KARIM BENZEMA", "HARRY KANE"], "Atacantul polonez", "5 goluri în 9 minute contra lui Wolfsburg", "A jucat la Bayern și Barcelona", "mediu", "Robert Lewandowski"),
    ("ZLATAN IBRAHIMOVIC", ["ROBERT LEWANDOWSKI", "THIERRY HENRY", "DIDIER DROGBA"], "Suedezul cu ego legendar", "Foarfeca de la 30 de metri", "'Un Zlatan nu dă probe'", "mediu", "Zlatan Ibrahimović"),
    ("DAVID BECKHAM", ["ZINEDINE ZIDANE", "RYAN GIGGS", "FRANK LAMPARD"], "Maestrul loviturilor libere", "Căsătorit cu o Spice Girl", "Patron la Inter Miami", "usor", "David Beckham"),
    ("ZINEDINE ZIDANE", ["RONALDINHO", "DAVID BECKHAM", "THIERRY HENRY"], "Poreclit 'Zizou'", "Lovitura de cap din finala din 2006", "Antrenor cu 3 Ligi ale Campionilor la rând", "mediu", "Zinedine Zidane"),
    ("RONALDINHO", ["NEYMAR", "RIVALDO", "KAKA"], "Zâmbetul magiei braziliene", "Balonul de Aur în 2005", "Aplaudat în picioare de fanii Realului pe Bernabéu", "mediu", "Ronaldinho"),
    ("PELE", ["DIEGO MARADONA", "GARRINCHA", "ZICO"], "'Regele fotbalului'", "3 Cupe Mondiale câștigate", "Legenda braziliană cu peste 1000 de goluri", "usor", "Pelé"),
    ("DIEGO MARADONA", ["PELE", "LIONEL MESSI", "RONALDINHO"], "'Mâna lui Dumnezeu'", "Golul secolului în 1986", "Zeul orașului Napoli", "usor", "Diego Maradona"),
    ("GHEORGHE HAGI", ["ADRIAN MUTU", "GICA POPESCU", "MIODRAG BELODEDICI"], "'Maradona din Carpați'", "Regele fotbalului românesc", "Patron și antrenor la Farul", "usor", "Gheorghe Hagi"),
    ("ADRIAN MUTU", ["GHEORGHE HAGI", "CIPRIAN MARICA", "FLORIN RADUCIOIU"], "Poreclit 'Briliantul'", "A jucat la Chelsea și Fiorentina", "Atacant român cu carieră lungă în Italia", "mediu", "Adrian Mutu"),
    ("CRISTIAN CHIVU", ["GICA POPESCU", "RAZVAN RAT", "COSMIN CONTRA"], "Căpitan la Ajax la doar 21 de ani", "Campion al Europei cu Inter în 2010", "Fundașul român cu cască de protecție", "mediu", "Cristian Chivu"),
    ("GICA POPESCU", ["GHEORGHE HAGI", "DAN PETRESCU", "MIODRAG BELODEDICI"], "Căpitan la FC Barcelona", "Fundașul Generației de Aur", "Cumnatul lui Hagi", "mediu", "Gheorghe Popescu"),
    ("SIMONA HALEP", ["SORANA CIRSTEA", "EMMA RADUCANU", "IRINA BEGU"], "Fost număr 1 mondial la tenis", "Campioană la Wimbledon în 2019", "Sportiva din Constanța", "usor", "Simona Halep"),
    ("NADIA COMANECI", ["LARISA IORDACHE", "CATALINA PONOR", "SIMONA AMANAR"], "Primul 10 perfect din istoria gimnasticii", "Eroina de la Montreal 1976", "'Zeița de la Montreal'", "usor", "Nadia Comăneci"),
    ("DAVID POPOVICI", ["ROBERT GLINTA", "CAELEB DRESSEL", "KYLE CHALMERS"], "Înotătorul-minune al României", "Aur olimpic la Paris 2024", "Recordman mondial la 100 m liber", "usor", "David Popovici"),
    ("SERENA WILLIAMS", ["VENUS WILLIAMS", "MARIA SHARAPOVA", "NAOMI OSAKA"], "23 de titluri de Grand Slam", "Regina tenisului american", "Sora ei e tot campioană", "usor", "Serena Williams"),
    ("NOVAK DJOKOVIC", ["ROGER FEDERER", "RAFAEL NADAL", "ANDY MURRAY"], "Sârbul cu cele mai multe Grand Slam-uri", "Poreclit 'Nole'", "Flexibilitate legendară pe teren", "usor", "Novak Djokovic"),
    ("ROGER FEDERER", ["NOVAK DJOKOVIC", "RAFAEL NADAL", "PETE SAMPRAS"], "Eleganța elvețiană", "8 titluri la Wimbledon", "Reverul cu o mână perfect", "usor", "Roger Federer"),
    ("RAFAEL NADAL", ["ROGER FEDERER", "NOVAK DJOKOVIC", "CARLOS ALCARAZ"], "'Regele zgurii'", "14 titluri la Roland Garros", "Stângaciul din Mallorca", "usor", "Rafael Nadal"),
    ("LEBRON JAMES", ["MICHAEL JORDAN", "KOBE BRYANT", "KEVIN DURANT"], "'King James'", "Recordul de puncte all-time în NBA", "A jucat alături de fiul său la Lakers", "usor", "LeBron James"),
    ("MICHAEL JORDAN", ["LEBRON JAMES", "KOBE BRYANT", "SCOTTIE PIPPEN"], "'Air Jordan'", "6 titluri cu Chicago Bulls", "Considerat GOAT-ul baschetului", "usor", "Michael Jordan"),
    ("KOBE BRYANT", ["MICHAEL JORDAN", "LEBRON JAMES", "SHAQUILLE ONEAL"], "'Black Mamba'", "81 de puncte într-un singur meci", "Legenda Lakers cu numerele 8 și 24", "mediu", "Kobe Bryant"),
    ("STEPHEN CURRY", ["KLAY THOMPSON", "KEVIN DURANT", "JAMES HARDEN"], "Cel mai bun shooter din istorie", "A revoluționat aruncarea de 3 puncte", "Vedeta Golden State Warriors", "mediu", "Stephen Curry"),
    ("USAIN BOLT", ["TYSON GAY", "CARL LEWIS", "MO FARAH"], "'Fulgerul' jamaican", "9.58 secunde la 100 de metri", "Poza cu fulgerul după curse", "usor", "Usain Bolt"),
    ("MICHAEL PHELPS", ["IAN THORPE", "CAELEB DRESSEL", "MARK SPITZ"], "23 de medalii olimpice de aur", "'Rechinul din Baltimore'", "Cel mai medaliat olimpic din istorie", "usor", "Michael Phelps"),
    ("LEWIS HAMILTON", ["MAX VERSTAPPEN", "SEBASTIAN VETTEL", "FERNANDO ALONSO"], "7 titluri mondiale în Formula 1", "S-a mutat la Ferrari în 2025", "Pilotul britanic cu numărul 44", "usor", "Lewis Hamilton"),
    ("MAX VERSTAPPEN", ["LEWIS HAMILTON", "CHARLES LECLERC", "LANDO NORRIS"], "'Olandezul zburător'", "Campion mondial cu Red Bull", "Fiul unui fost pilot de Formula 1", "usor", "Max Verstappen"),
    ("MICHAEL SCHUMACHER", ["LEWIS HAMILTON", "SEBASTIAN VETTEL", "AYRTON SENNA"], "Legenda Ferrari cu 7 titluri", "'Baronul roșu' al Formulei 1", "91 de victorii în Grand Prix-uri", "mediu", "Michael Schumacher"),
    ("MIKE TYSON", ["MUHAMMAD ALI", "FLOYD MAYWEATHER", "EVANDER HOLYFIELD"], "'Iron Mike'", "Cel mai tânăr campion la categoria grea", "A mușcat o ureche în ring", "usor", "Mike Tyson"),
    ("MUHAMMAD ALI", ["MIKE TYSON", "GEORGE FOREMAN", "JOE FRAZIER"], "'Float like a butterfly, sting like a bee'", "Poreclit 'The Greatest'", "Meciul Rumble in the Jungle", "mediu", "Muhammad Ali"),
    ("CONOR MCGREGOR", ["KHABIB NURMAGOMEDOV", "JON JONES", "ISRAEL ADESANYA"], "'The Notorious'", "Irlandezul vedetă din UFC", "Campion simultan la două categorii", "mediu", "Conor McGregor"),
    ("KHABIB NURMAGOMEDOV", ["CONOR MCGREGOR", "ISLAM MAKHACHEV", "JON JONES"], "Retras neînvins, 29-0", "'Vulturul' din Daghestan", "L-a învins pe McGregor în 2018", "greu", "Khabib Nurmagomedov"),
    ("TIGER WOODS", ["RORY MCILROY", "PHIL MICKELSON", "JACK NICKLAUS"], "Legenda golfului", "15 turnee majore câștigate", "Revenirea istorică de la Masters 2019", "mediu", "Tiger Woods"),
    ("TOM BRADY", ["PEYTON MANNING", "PATRICK MAHOMES", "AARON RODGERS"], "7 inele de Super Bowl", "GOAT-ul fotbalului american", "Ales abia în runda a 6-a la draft", "greu", "Tom Brady"),
    ("REAL MADRID", ["FC BARCELONA", "ATLETICO MADRID", "BAYERN MUNCHEN"], "'Los Blancos'", "Recordul de Ligi ale Campionilor", "Stadionul Santiago Bernabéu", "usor", "Real Madrid CF"),
    ("FC BARCELONA", ["REAL MADRID", "SEVILLA", "MANCHESTER CITY"], "'Mai mult decât un club'", "Stadionul Camp Nou", "Tiki-taka și academia La Masia", "usor", "FC Barcelona"),
    ("MANCHESTER UNITED", ["MANCHESTER CITY", "LIVERPOOL", "ARSENAL"], "'Diavolii Roșii'", "Stadionul Old Trafford", "Era de aur cu Sir Alex Ferguson", "usor", "Manchester United F.C."),
    ("LIVERPOOL", ["MANCHESTER UNITED", "EVERTON", "CHELSEA"], "'You'll Never Walk Alone'", "Stadionul Anfield", "Pasărea Liver pe siglă", "usor", "Liverpool F.C."),
    ("JUVENTUS", ["AC MILAN", "INTER MILANO", "NAPOLI"], "'Bătrâna Doamnă'", "Echipa alb-negră din Torino", "Recordul de titluri din Serie A", "mediu", "Juventus FC"),
    ("BAYERN MUNCHEN", ["BORUSSIA DORTMUND", "RB LEIPZIG", "SCHALKE 04"], "Gigantul Bavariei", "Stadionul Allianz Arena", "Campioana aproape eternă a Germaniei", "mediu", "FC Bayern Munich"),
    ("PSG", ["OLYMPIQUE MARSEILLE", "AS MONACO", "OLYMPIQUE LYON"], "Clubul orașului cu Turnul Eiffel", "Messi, Neymar și Mbappé au jucat aici simultan", "Stadionul Parc des Princes", "mediu", "Paris Saint-Germain F.C."),
    ("FCSB", ["DINAMO BUCURESTI", "RAPID BUCURESTI", "CFR CLUJ"], "Roș-albaștrii Bucureștiului", "Echipa patronată de Gigi Becali", "Câștigătoarea Cupei Campionilor din 1986 (ca Steaua)", "usor", "FCSB"),
    ("DINAMO BUCURESTI", ["FCSB", "RAPID BUCURESTI", "UNIVERSITATEA CRAIOVA"], "'Câinii roșii'", "Rivala eternă din Ștefan cel Mare", "Echipa alb-roșie a Bucureștiului", "usor", "FC Dinamo București"),
    ("CFR CLUJ", ["UNIVERSITATEA CLUJ", "FCSB", "FARUL CONSTANTA"], "Feroviarii din Gruia", "Titluri consecutive în Liga 1", "Vișiniul Ardealului", "mediu", "CFR Cluj"),
    ("CUPA MONDIALA", ["LIGA CAMPIONILOR", "EUROPA LEAGUE", "CUPA ROMANIEI"], "Trofeul suprem al fotbalului", "Se decernează o dată la 4 ani", "Trofeu din aur de 18 carate", "usor", "FIFA World Cup Trophy"),
]

ROMANIA = [
    ("CASTELUL BRAN", ["CASTELUL PELES", "CETATEA CORVINILOR", "CETATEA RASNOV"], "'Castelul lui Dracula'", "Între Bucegi și Piatra Craiului", "Cel mai vizitat castel din România", "usor", "Bran Castle"),
    ("CASTELUL PELES", ["CASTELUL BRAN", "CETATEA CORVINILOR", "PALATUL COTROCENI"], "Reședința regală de la Sinaia", "Construit de regele Carol I", "Primul castel electrificat din Europa", "usor", "Peleș Castle"),
    ("PALATUL PARLAMENTULUI", ["ATENEUL ROMAN", "PALATUL COTROCENI", "CASA PRESEI"], "A doua cea mai mare clădire administrativă din lume", "Numit și 'Casa Poporului'", "Construit în epoca Ceaușescu", "usor", "Palace of the Parliament"),
    ("ATENEUL ROMAN", ["OPERA NATIONALA", "PALATUL CEC", "TEATRUL NATIONAL"], "Sala de concerte emblemă a Bucureștiului", "Aici cântă Filarmonica George Enescu", "Cupolă și coloane neoclasice", "mediu", "Romanian Athenaeum"),
    ("ARCUL DE TRIUMF", ["ATENEUL ROMAN", "PODUL MINCIUNILOR", "TURNUL CHINDIEI"], "Monument din nordul Bucureștiului", "Inspirat de cel din Paris", "Parada de 1 Decembrie trece pe sub el", "mediu", "Arcul de Triumf"),
    ("TRANSFAGARASAN", ["TRANSALPINA", "VALEA PRAHOVEI", "PASUL TIHUTA"], "'Cea mai frumoasă șosea din lume' (Top Gear)", "Traversează Munții Făgăraș", "Construit la ordinul lui Ceaușescu", "usor", "Transfăgărășan"),
    ("TRANSALPINA", ["TRANSFAGARASAN", "VALEA OLTULUI", "PASUL PRISLOP"], "'Drumul Regelui'", "Cea mai înaltă șosea din România", "Traversează Munții Parâng", "mediu", "Transalpina"),
    ("DELTA DUNARII", ["BALTA BRAILEI", "LACUL RAZELM", "LACUL SNAGOV"], "Paradisul pelicanilor", "Patrimoniu mondial UNESCO", "Fluviul se varsă în mare prin trei brațe", "usor", "Danube Delta"),
    ("SARMALE", ["MICI", "PIFTIE", "CHIFTELE"], "Rulouri de varză cu umplutură de carne", "Nelipsite de Crăciun", "Se servesc cu mămăligă și smântână", "usor", "Sarma (food)"),
    ("MAMALIGA", ["SARMALE", "ZACUSCA", "BULZ"], "'Pâinea' galbenă a țăranului", "Se fierbe din mălai", "Merge perfect cu brânză și smântână", "usor", "Mămăligă"),
    ("MICI", ["SARMALE", "CARNATI", "CHIFTELE"], "Nelipsiți de 1 Mai la grătar", "Se mănâncă tradițional cu muștar", "Rulouri de carne tocată fără membrană", "usor", "Mititei"),
    ("COZONAC", ["CHEC", "PASCA", "PLACINTA"], "Desertul sărbătorilor", "Cu nucă, cacao sau rahat", "Aluat dospit împletit", "usor", "Cozonac"),
    ("PAPANASI", ["GOGOSI", "CLATITE", "GALUSTE"], "Desert prăjit cu brânză dulce", "Cu smântână și dulceață de afine deasupra", "Vedeta meniurilor tradiționale", "usor", "Papanași"),
    ("ZACUSCA", ["SALATA DE VINETE", "ICRE", "PASTA DE ARDEI"], "Conserva toamnei românești", "Din vinete, ardei copți și ceapă", "Se pune la borcan pentru iarnă", "mediu", "Zacuscă"),
    ("TUICA", ["PALINCA", "VISINATA", "AFINATA"], "Băutura tradițională din prune", "'Un păhărel' înainte de masă", "Distilată toamna în cazan de cupru", "mediu", "Țuică"),
    ("IA ROMANEASCA", ["CATRINTA", "MARAMA", "OPINCILE"], "Bluza tradițională brodată", "Celebrată în fiecare an pe 24 iunie", "L-a inspirat pe pictorul Matisse", "mediu", "Romanian blouse"),
    ("MARTISOR", ["COCARDA", "TURTA DULCE", "SORCOVA"], "Șnur alb-roșu dăruit pe 1 Martie", "Vestitorul primăverii", "Se oferă doamnelor și domnișoarelor", "usor", "Mărțișor"),
    ("VLAD TEPES", ["STEFAN CEL MARE", "MIRCEA CEL BATRAN", "MIHAI VITEAZUL"], "Domnitorul care l-a inspirat pe Dracula", "Îi pedepsea pe hoți în țeapă", "Domn al Țării Românești", "usor", "Vlad the Impaler"),
    ("STEFAN CEL MARE", ["VLAD TEPES", "MIHAI VITEAZUL", "ALEXANDRU CEL BUN"], "Domnitorul Moldovei timp de 47 de ani", "A ridicat câte o biserică după fiecare bătălie", "'Atletul lui Hristos'", "usor", "Stephen the Great"),
    ("MIHAI VITEAZUL", ["STEFAN CEL MARE", "VLAD TEPES", "CONSTANTIN BRANCOVEANU"], "Prima unire a celor trei țări române", "Domnitor în jurul anului 1600", "Statuia sa e în Piața Universității", "usor", "Michael the Brave"),
    ("DECEBAL", ["BUREBISTA", "TRAIAN", "DROMIHETE"], "Ultimul rege al dacilor", "Chipul său e sculptat în stâncă la Dunăre", "Învins de împăratul Traian", "mediu", "Rock sculpture of Decebalus"),
    ("MIHAI EMINESCU", ["ION CREANGA", "GEORGE COSBUC", "VASILE ALECSANDRI"], "'Luceafărul' poeziei românești", "Născut la Ipotești", "Chipul de pe bancnota de 500 de lei", "usor", "Mihai Eminescu"),
    ("ION CREANGA", ["MIHAI EMINESCU", "ION LUCA CARAGIALE", "MIHAIL SADOVEANU"], "'Amintiri din copilărie'", "Povestitorul din Humulești", "Prieten bun cu Eminescu", "usor", "Ion Creangă"),
    ("CONSTANTIN BRANCUSI", ["GEORGE ENESCU", "NICOLAE GRIGORESCU", "THEODOR AMAN"], "Părintele sculpturii moderne", "Născut la Hobița, Gorj", "A creat 'Pasărea măiastră'", "mediu", "Constantin Brâncuși"),
    ("COLOANA INFINITULUI", ["POARTA SARUTULUI", "MASA TACERII", "PASAREA MAIASTRA"], "Sculptură de aproape 30 de metri la Târgu Jiu", "Omagiu eroilor din Primul Război Mondial", "Module romboidale repetate spre cer", "mediu", "Endless Column"),
    ("GEORGE ENESCU", ["CIPRIAN PORUMBESCU", "GHEORGHE ZAMFIR", "DINU LIPATTI"], "Cel mai mare compozitor român", "'Rapsodia Română'", "Festivalul internațional îi poartă numele", "mediu", "George Enescu"),
    ("HENRI COANDA", ["TRAIAN VUIA", "AUREL VLAICU", "HERMANN OBERTH"], "Pionierul avionului cu reacție", "Aeroportul Otopeni îi poartă numele", "A descoperit 'efectul Coandă'", "mediu", "Henri Coandă"),
    ("TRAIAN VUIA", ["HENRI COANDA", "AUREL VLAICU", "GEORGE CONSTANTINESCU"], "Zbor doar cu mijloacele de la bord, în 1906", "Pionier bănățean al aviației", "Aeroportul din Timișoara îi poartă numele", "greu", "Traian Vuia"),
    ("ALBA CAROLINA", ["CETATEA RASNOV", "CETATEA SIGHISOARA", "CETATEA FAGARAS"], "Cetatea în formă de stea din Alba Iulia", "Aici s-a înfăptuit Marea Unire din 1918", "Fortificație Vauban cu 7 bastioane", "mediu", "Alba Carolina Citadel"),
    ("SIGHISOARA", ["BRASOV", "SIBIU", "MEDIAS"], "Cetate medievală locuită, în patrimoniul UNESCO", "Turnul cu Ceas o veghează", "Aici s-a născut Vlad Țepeș", "mediu", "Sighișoara"),
    ("SALINA TURDA", ["SALINA PRAID", "SALINA SLANIC", "SALINA CACICA"], "Mină de sare cu parc de distracții", "Roată panoramică în subteran", "În apropiere de Cluj", "mediu", "Salina Turda"),
    ("MANASTIREA VORONET", ["MANASTIREA PUTNA", "MANASTIREA SUCEVITA", "MANASTIREA MOLDOVITA"], "'Capela Sixtină a Estului'", "Celebrul 'albastru de Voroneț'", "Ctitorită de Ștefan cel Mare", "mediu", "Voroneț Monastery"),
    ("CIMITIRUL VESEL", ["MANASTIREA BARSANA", "CIMITIRUL BELLU", "MUZEUL SATULUI"], "Cruci albastre cu versuri hazlii", "Se află la Săpânța, în Maramureș", "Moartea luată în râs", "mediu", "Merry Cemetery"),
    ("SFINXUL DIN BUCEGI", ["BABELE", "VARFUL OMU", "CRUCEA CARAIMAN"], "Stâncă cu chip uman la 2216 metri", "Se află lângă Babele", "Format prin eroziunea vântului", "usor", "Bucegi Sphinx"),
    ("BABELE", ["SFINXUL DIN BUCEGI", "VULCANII NOROIOSI", "DETUNATELE"], "'Ciupercile' de piatră din Bucegi", "La câțiva pași de Sfinx", "Sculptate de vânt și ploaie", "greu", "Babele"),
    ("VULCANII NOROIOSI", ["BABELE", "PESTERA URSILOR", "RAPA ROSIE"], "Peisaj selenar în județul Buzău", "'Fierb' noroi rece la suprafață", "La Pâclele Mari și Pâclele Mici", "mediu", "Berca Mud Volcanoes"),
    ("CASCADA BIGAR", ["CASCADA CAILOR", "CASCADA URLATOAREA", "CASCADA VALUL MIRESEI"], "Perdea de apă peste mușchi verde", "În Cheile Nerei, în Banat", "S-a prăbușit parțial în 2021", "greu", "Bigăr Waterfall"),
    ("LACUL BALEA", ["LACUL SFANTA ANA", "LACUL ROSU", "LACUL VIDRARU"], "Lac glaciar la capătul Transfăgărășanului", "Aici se construiește iarna hotelul de gheață", "În Munții Făgăraș, la 2034 metri", "mediu", "Bâlea Lake"),
    ("LACUL SFANTA ANA", ["LACUL BALEA", "LACUL ROSU", "LACUL URSU"], "Singurul lac vulcanic din România", "S-a format în craterul Ciomatu", "Lângă Băile Tușnad", "greu", "Lake Sfânta Ana"),
    ("PESTERA SCARISOARA", ["PESTERA URSILOR", "PESTERA MUIERILOR", "PESTERA POLOVRAGI"], "Adăpostește un ghețar subteran", "În Munții Apuseni", "Gheață veche de peste 3500 de ani", "greu", "Scărișoara Cave"),
    ("CETATEA CORVINILOR", ["CASTELUL BRAN", "CASTELUL PELES", "CETATEA NEAMT"], "Castel gotic la Hunedoara", "A aparținut familiei lui Iancu de Hunedoara", "Printre cele mai frumoase castele gotice din Europa", "mediu", "Corvin Castle"),
    ("STEAGUL ROMANIEI", ["STEMA ROMANIEI", "DRAPELUL UE", "STEAGUL FRANTEI"], "Albastru, galben și roșu", "Tricolor cu benzi verticale", "Aproape identic cu al Ciadului", "usor", "Flag of Romania"),
    ("STEMA ROMANIEI", ["STEAGUL ROMANIEI", "SIGILIUL DACIEI", "STEMA MOLDOVEI"], "Acvila de aur cu cruce în cioc", "Scut cu provinciile istorice", "Apare pe pașaportul românesc", "mediu", "Coat of arms of Romania"),
    ("LEUL ROMANESC", ["EURO", "FORINTUL", "LEVA"], "Moneda națională", "Subdiviziunea se numește ban", "RON pe scurt", "usor", "Romanian leu"),
    ("VARFUL MOLDOVEANU", ["VARFUL NEGOIU", "VARFUL OMU", "VARFUL PARANGUL MARE"], "'Acoperișul' României", "2544 de metri altitudine", "În Munții Făgăraș", "mediu", "Moldoveanu Peak"),
    ("CAZINOUL DIN CONSTANTA", ["ATENEUL ROMAN", "PALATUL CULTURII IASI", "CAZINOUL SINAIA"], "Bijuterie Art Nouveau pe faleză", "Simbolul orașului de la malul mării", "Restaurat și redeschis recent", "greu", "Constanța Casino"),
    ("DACIA 1300", ["DACIA LOGAN", "ARO 244", "OLTCIT"], "Mașina 'epocii de aur'", "Visul oricărui român înainte de '89", "Fabricată la Mioveni din 1969", "mediu", "Dacia 1300"),
    ("MANASTIREA CURTEA DE ARGES", ["MANASTIREA VORONET", "MANASTIREA PUTNA", "MANASTIREA HOREZU"], "Legată de legenda Meșterului Manole", "Necropola regilor României", "Turle răsucite unice", "greu", "Curtea de Argeș Cathedral"),
    ("MUZEUL SATULUI", ["MUZEUL ANTIPA", "MUZEUL TARANULUI", "MUZEUL ASTRA"], "Case țărănești autentice, în aer liber", "În Parcul Herăstrău din București", "Fondat de sociologul Dimitrie Gusti", "greu", "Dimitrie Gusti National Village Museum"),
    ("CHEILE BICAZULUI", ["CHEILE NEREI", "CHEILE TURZII", "DEFILEUL JIULUI"], "Canion spectaculos între Neamț și Harghita", "Drumul trece printre pereți de 300 de metri", "Duce spre Lacul Roșu", "mediu", "Bicaz Canyon"),
]

MODES = [
    ("masini", "mas", "Bolizi & branduri auto", "#C0392B", MASINI),
    ("celebritati", "cel", "Vedete & staruri", "#8E44AD", CELEBRITATI),
    ("sport", "spo", "Fotbaliști & echipe", "#16A085", SPORT),
    ("romania", "rom", "Cultură & simboluri", "#2C3E90", ROMANIA),
]


def main():
    for mode_id, prefix, descriere, culoare, rows in MODES:
        intrebari = []
        for i, (raspuns, gresite, h1, h2, h3, dif, cautare) in enumerate(rows, 1):
            intrebari.append({
                "id": f"{prefix}_{i:03d}",
                "raspuns": raspuns,
                "variante": [raspuns] + gresite,
                "hint_1": h1,
                "hint_2": h2,
                "hint_3": h3,
                "dificultate": dif,
                "puncte_max": PUNCTE[dif],
                "imagine_cautare": cautare,
                "imagine_sursa": "wikipedia",
            })
        data = {
            "version": "1.0",
            "limba": "ro",
            "categorii": {
                mode_id: {
                    "mod": "4_variante",
                    "culoare_tema": culoare,
                    "descriere": descriere,
                    "intrebari": intrebari,
                }
            },
        }
        folder = os.path.join("assets", "continut", mode_id)
        os.makedirs(os.path.join(folder, "poze"), exist_ok=True)
        out = os.path.join(folder, "intrebari.json")
        with open(out, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"{out}: {len(intrebari)} intrebari")


if __name__ == "__main__":
    main()
